// GENERATED FILE. Edit config/regional-pricing.json and run npm run pricing:generate.
// Source SHA-256: 9ae08e84662a2e22084cbc8735793d9af321c2877a6a91e27847e8e541ed0749

export interface RegionalPricingMarket {
  readonly id: string;
  readonly currencyCode: string;
  readonly locale: string;
  readonly minorUnits: number;
  readonly monthly: number;
  readonly yearly: number;
  readonly lifetime: number;
  readonly compareAtMonthly: number;
  readonly compareAtYearly: number;
}

export const REGIONAL_PRICING_CATALOG_VERSION = 1;
export const DEFAULT_REGIONAL_PRICING_MARKET_ID = "usd";
export const REGIONAL_PRICING_MARKETS = {
  aed: {
    id: "aed",
    currencyCode: "AED",
    locale: "ar-AE",
    minorUnits: 2,
    monthly: 1499,
    yearly: 9999,
    lifetime: 34999,
    compareAtMonthly: 2399,
    compareAtYearly: 15999,
  },
  aud: {
    id: "aud",
    currencyCode: "AUD",
    locale: "en-AU",
    minorUnits: 2,
    monthly: 599,
    yearly: 3999,
    lifetime: 14999,
    compareAtMonthly: 959,
    compareAtYearly: 6399,
  },
  brl: {
    id: "brl",
    currencyCode: "BRL",
    locale: "pt-BR",
    minorUnits: 2,
    monthly: 2490,
    yearly: 14990,
    lifetime: 59990,
    compareAtMonthly: 3984,
    compareAtYearly: 23984,
  },
  cad: {
    id: "cad",
    currencyCode: "CAD",
    locale: "en-CA",
    minorUnits: 2,
    monthly: 1499,
    yearly: 9999,
    lifetime: 19999,
    compareAtMonthly: 2399,
    compareAtYearly: 15999,
  },
  chf: {
    id: "chf",
    currencyCode: "CHF",
    locale: "de-CH",
    minorUnits: 2,
    monthly: 300,
    yearly: 2000,
    lifetime: 8000,
    compareAtMonthly: 480,
    compareAtYearly: 3200,
  },
  clp: {
    id: "clp",
    currencyCode: "CLP",
    locale: "es-CL",
    minorUnits: 0,
    monthly: 4990,
    yearly: 29990,
    lifetime: 99990,
    compareAtMonthly: 7984,
    compareAtYearly: 47984,
  },
  cny: {
    id: "cny",
    currencyCode: "CNY",
    locale: "zh-CN",
    minorUnits: 2,
    monthly: 2800,
    yearly: 16800,
    lifetime: 59800,
    compareAtMonthly: 4480,
    compareAtYearly: 26880,
  },
  cop: {
    id: "cop",
    currencyCode: "COP",
    locale: "es-CO",
    minorUnits: 0,
    monthly: 19900,
    yearly: 119900,
    lifetime: 399900,
    compareAtMonthly: 31840,
    compareAtYearly: 191840,
  },
  czk: {
    id: "czk",
    currencyCode: "CZK",
    locale: "cs-CZ",
    minorUnits: 2,
    monthly: 9900,
    yearly: 69900,
    lifetime: 249000,
    compareAtMonthly: 15840,
    compareAtYearly: 111840,
  },
  dkk: {
    id: "dkk",
    currencyCode: "DKK",
    locale: "da-DK",
    minorUnits: 2,
    monthly: 3900,
    yearly: 19900,
    lifetime: 79900,
    compareAtMonthly: 6240,
    compareAtYearly: 31840,
  },
  egp: {
    id: "egp",
    currencyCode: "EGP",
    locale: "ar-EG",
    minorUnits: 2,
    monthly: 19999,
    yearly: 129999,
    lifetime: 499999,
    compareAtMonthly: 31999,
    compareAtYearly: 207999,
  },
  eur: {
    id: "eur",
    currencyCode: "EUR",
    locale: "en-IE",
    minorUnits: 2,
    monthly: 499,
    yearly: 2999,
    lifetime: 9999,
    compareAtMonthly: 799,
    compareAtYearly: 4799,
  },
  eur_2: {
    id: "eur_2",
    currencyCode: "EUR",
    locale: "en-IE",
    minorUnits: 2,
    monthly: 499,
    yearly: 2999,
    lifetime: 9999,
    compareAtMonthly: 799,
    compareAtYearly: 4799,
  },
  gbp: {
    id: "gbp",
    currencyCode: "GBP",
    locale: "en-GB",
    minorUnits: 2,
    monthly: 399,
    yearly: 2499,
    lifetime: 8999,
    compareAtMonthly: 639,
    compareAtYearly: 3999,
  },
  hkd: {
    id: "hkd",
    currencyCode: "HKD",
    locale: "zh-HK",
    minorUnits: 2,
    monthly: 3200,
    yearly: 18800,
    lifetime: 68800,
    compareAtMonthly: 5120,
    compareAtYearly: 30080,
  },
  huf: {
    id: "huf",
    currencyCode: "HUF",
    locale: "hu-HU",
    minorUnits: 0,
    monthly: 1790,
    yearly: 9990,
    lifetime: 39990,
    compareAtMonthly: 2864,
    compareAtYearly: 15984,
  },
  idr: {
    id: "idr",
    currencyCode: "IDR",
    locale: "id-ID",
    minorUnits: 0,
    monthly: 69000,
    yearly: 399000,
    lifetime: 1499000,
    compareAtMonthly: 110400,
    compareAtYearly: 638400,
  },
  ils: {
    id: "ils",
    currencyCode: "ILS",
    locale: "he-IL",
    minorUnits: 2,
    monthly: 1490,
    yearly: 8990,
    lifetime: 29990,
    compareAtMonthly: 2384,
    compareAtYearly: 14384,
  },
  inr: {
    id: "inr",
    currencyCode: "INR",
    locale: "en-IN",
    minorUnits: 2,
    monthly: 39900,
    yearly: 249900,
    lifetime: 990000,
    compareAtMonthly: 63840,
    compareAtYearly: 399840,
  },
  jpy: {
    id: "jpy",
    currencyCode: "JPY",
    locale: "ja-JP",
    minorUnits: 0,
    monthly: 600,
    yearly: 4000,
    lifetime: 15000,
    compareAtMonthly: 960,
    compareAtYearly: 6400,
  },
  krw: {
    id: "krw",
    currencyCode: "KRW",
    locale: "ko-KR",
    minorUnits: 0,
    monthly: 6600,
    yearly: 44000,
    lifetime: 149000,
    compareAtMonthly: 10560,
    compareAtYearly: 70400,
  },
  kzt: {
    id: "kzt",
    currencyCode: "KZT",
    locale: "kk-KZ",
    minorUnits: 2,
    monthly: 249000,
    yearly: 1499000,
    lifetime: 4999000,
    compareAtMonthly: 398400,
    compareAtYearly: 2398400,
  },
  mxn: {
    id: "mxn",
    currencyCode: "MXN",
    locale: "es-MX",
    minorUnits: 2,
    monthly: 8900,
    yearly: 49900,
    lifetime: 199900,
    compareAtMonthly: 14240,
    compareAtYearly: 79840,
  },
  myr: {
    id: "myr",
    currencyCode: "MYR",
    locale: "ms-MY",
    minorUnits: 2,
    monthly: 1990,
    yearly: 11990,
    lifetime: 39990,
    compareAtMonthly: 3184,
    compareAtYearly: 19184,
  },
  ngn: {
    id: "ngn",
    currencyCode: "NGN",
    locale: "en-NG",
    minorUnits: 2,
    monthly: 690000,
    yearly: 3990000,
    lifetime: 14990000,
    compareAtMonthly: 1104000,
    compareAtYearly: 6384000,
  },
  nok: {
    id: "nok",
    currencyCode: "NOK",
    locale: "nb-NO",
    minorUnits: 2,
    monthly: 4900,
    yearly: 29900,
    lifetime: 99900,
    compareAtMonthly: 7840,
    compareAtYearly: 47840,
  },
  nzd: {
    id: "nzd",
    currencyCode: "NZD",
    locale: "en-NZ",
    minorUnits: 2,
    monthly: 699,
    yearly: 4999,
    lifetime: 14999,
    compareAtMonthly: 1119,
    compareAtYearly: 7999,
  },
  pen: {
    id: "pen",
    currencyCode: "PEN",
    locale: "es-PE",
    minorUnits: 2,
    monthly: 1790,
    yearly: 9990,
    lifetime: 39990,
    compareAtMonthly: 2864,
    compareAtYearly: 15984,
  },
  php: {
    id: "php",
    currencyCode: "PHP",
    locale: "en-PH",
    minorUnits: 2,
    monthly: 24900,
    yearly: 149000,
    lifetime: 599000,
    compareAtMonthly: 39840,
    compareAtYearly: 238400,
  },
  pkr: {
    id: "pkr",
    currencyCode: "PKR",
    locale: "en-PK",
    minorUnits: 2,
    monthly: 110000,
    yearly: 690000,
    lifetime: 2490000,
    compareAtMonthly: 176000,
    compareAtYearly: 1104000,
  },
  pln: {
    id: "pln",
    currencyCode: "PLN",
    locale: "pl-PL",
    minorUnits: 2,
    monthly: 1999,
    yearly: 9999,
    lifetime: 39999,
    compareAtMonthly: 3199,
    compareAtYearly: 15999,
  },
  qar: {
    id: "qar",
    currencyCode: "QAR",
    locale: "ar-QA",
    minorUnits: 2,
    monthly: 1499,
    yearly: 9999,
    lifetime: 29999,
    compareAtMonthly: 2399,
    compareAtYearly: 15999,
  },
  ron: {
    id: "ron",
    currencyCode: "RON",
    locale: "ro-RO",
    minorUnits: 2,
    monthly: 1999,
    yearly: 12999,
    lifetime: 49999,
    compareAtMonthly: 3199,
    compareAtYearly: 20799,
  },
  rub: {
    id: "rub",
    currencyCode: "RUB",
    locale: "ru-RU",
    minorUnits: 2,
    monthly: 34900,
    yearly: 229000,
    lifetime: 799000,
    compareAtMonthly: 55840,
    compareAtYearly: 366400,
  },
  sar: {
    id: "sar",
    currencyCode: "SAR",
    locale: "ar-SA",
    minorUnits: 2,
    monthly: 1799,
    yearly: 9999,
    lifetime: 39999,
    compareAtMonthly: 2879,
    compareAtYearly: 15999,
  },
  sek: {
    id: "sek",
    currencyCode: "SEK",
    locale: "sv-SE",
    minorUnits: 2,
    monthly: 4900,
    yearly: 29900,
    lifetime: 119500,
    compareAtMonthly: 7840,
    compareAtYearly: 47840,
  },
  sgd: {
    id: "sgd",
    currencyCode: "SGD",
    locale: "en-SG",
    minorUnits: 2,
    monthly: 598,
    yearly: 3498,
    lifetime: 12998,
    compareAtMonthly: 957,
    compareAtYearly: 5597,
  },
  thb: {
    id: "thb",
    currencyCode: "THB",
    locale: "th-TH",
    minorUnits: 2,
    monthly: 14900,
    yearly: 99900,
    lifetime: 299000,
    compareAtMonthly: 23840,
    compareAtYearly: 159840,
  },
  try: {
    id: "try",
    currencyCode: "TRY",
    locale: "tr-TR",
    minorUnits: 2,
    monthly: 19999,
    yearly: 129999,
    lifetime: 499999,
    compareAtMonthly: 31999,
    compareAtYearly: 207999,
  },
  twd: {
    id: "twd",
    currencyCode: "TWD",
    locale: "zh-TW",
    minorUnits: 2,
    monthly: 12000,
    yearly: 79000,
    lifetime: 299000,
    compareAtMonthly: 19200,
    compareAtYearly: 126400,
  },
  tzs: {
    id: "tzs",
    currencyCode: "TZS",
    locale: "sw-TZ",
    minorUnits: 2,
    monthly: 1190000,
    yearly: 6990000,
    lifetime: 24990000,
    compareAtMonthly: 1904000,
    compareAtYearly: 11184000,
  },
  usd: {
    id: "usd",
    currencyCode: "USD",
    locale: "en-US",
    minorUnits: 2,
    monthly: 1099,
    yearly: 7999,
    lifetime: 14999,
    compareAtMonthly: 1759,
    compareAtYearly: 12799,
  },
  usd_2: {
    id: "usd_2",
    currencyCode: "USD",
    locale: "en-US",
    minorUnits: 2,
    monthly: 1099,
    yearly: 7999,
    lifetime: 14999,
    compareAtMonthly: 1759,
    compareAtYearly: 12799,
  },
  usd_3: {
    id: "usd_3",
    currencyCode: "USD",
    locale: "en-US",
    minorUnits: 2,
    monthly: 1099,
    yearly: 7999,
    lifetime: 14999,
    compareAtMonthly: 1759,
    compareAtYearly: 12799,
  },
  usd_4: {
    id: "usd_4",
    currencyCode: "USD",
    locale: "en-US",
    minorUnits: 2,
    monthly: 1099,
    yearly: 7999,
    lifetime: 14999,
    compareAtMonthly: 1759,
    compareAtYearly: 12799,
  },
  vnd: {
    id: "vnd",
    currencyCode: "VND",
    locale: "vi-VN",
    minorUnits: 0,
    monthly: 119000,
    yearly: 799000,
    lifetime: 2999000,
    compareAtMonthly: 190400,
    compareAtYearly: 1278400,
  },
  zar: {
    id: "zar",
    currencyCode: "ZAR",
    locale: "en-ZA",
    minorUnits: 2,
    monthly: 7999,
    yearly: 49999,
    lifetime: 199999,
    compareAtMonthly: 12799,
    compareAtYearly: 79999,
  },
} as const satisfies Record<string, RegionalPricingMarket>;
export const REGIONAL_PRICING_COUNTRY_TO_MARKET = {
  AE: "aed",
  AU: "aud",
  BR: "brl",
  CA: "cad",
  CH: "chf",
  CL: "clp",
  CN: "cny",
  CO: "cop",
  CZ: "czk",
  DK: "dkk",
  EG: "egp",
  ME: "eur",
  AT: "eur_2",
  BA: "eur_2",
  BE: "eur_2",
  BG: "eur_2",
  CY: "eur_2",
  DE: "eur_2",
  EE: "eur_2",
  ES: "eur_2",
  FI: "eur_2",
  FR: "eur_2",
  GR: "eur_2",
  HR: "eur_2",
  IE: "eur_2",
  IT: "eur_2",
  LT: "eur_2",
  LU: "eur_2",
  LV: "eur_2",
  MT: "eur_2",
  NL: "eur_2",
  PT: "eur_2",
  RS: "eur_2",
  SI: "eur_2",
  SK: "eur_2",
  XK: "eur_2",
  GB: "gbp",
  HK: "hkd",
  HU: "huf",
  ID: "idr",
  IL: "ils",
  IN: "inr",
  JP: "jpy",
  KR: "krw",
  KZ: "kzt",
  MX: "mxn",
  MY: "myr",
  NG: "ngn",
  NO: "nok",
  NZ: "nzd",
  PE: "pen",
  PH: "php",
  PK: "pkr",
  PL: "pln",
  QA: "qar",
  RO: "ron",
  RU: "rub",
  SA: "sar",
  SE: "sek",
  SG: "sgd",
  TH: "thb",
  TR: "try",
  TW: "twd",
  TZ: "tzs",
  US: "usd",
  AF: "usd_2",
  AG: "usd_2",
  AI: "usd_2",
  AO: "usd_2",
  AR: "usd_2",
  BF: "usd_2",
  BM: "usd_2",
  BN: "usd_2",
  BO: "usd_2",
  BT: "usd_2",
  BW: "usd_2",
  BZ: "usd_2",
  CD: "usd_2",
  CG: "usd_2",
  CR: "usd_2",
  CV: "usd_2",
  DM: "usd_2",
  DO: "usd_2",
  DZ: "usd_2",
  EC: "usd_2",
  FJ: "usd_2",
  FM: "usd_2",
  GA: "usd_2",
  GD: "usd_2",
  GM: "usd_2",
  GT: "usd_2",
  GW: "usd_2",
  GY: "usd_2",
  HN: "usd_2",
  IQ: "usd_2",
  JM: "usd_2",
  JO: "usd_2",
  KN: "usd_2",
  KW: "usd_2",
  KY: "usd_2",
  LB: "usd_2",
  LC: "usd_2",
  LK: "usd_2",
  LR: "usd_2",
  LY: "usd_2",
  MA: "usd_2",
  MG: "usd_2",
  MK: "usd_2",
  ML: "usd_2",
  MM: "usd_2",
  MN: "usd_2",
  MO: "usd_2",
  MR: "usd_2",
  MS: "usd_2",
  MV: "usd_2",
  MW: "usd_2",
  MZ: "usd_2",
  NA: "usd_2",
  NE: "usd_2",
  NI: "usd_2",
  NR: "usd_2",
  OM: "usd_2",
  PA: "usd_2",
  PG: "usd_2",
  PW: "usd_2",
  PY: "usd_2",
  RW: "usd_2",
  SB: "usd_2",
  SC: "usd_2",
  SL: "usd_2",
  ST: "usd_2",
  SV: "usd_2",
  SZ: "usd_2",
  TC: "usd_2",
  TD: "usd_2",
  TM: "usd_2",
  TN: "usd_2",
  TO: "usd_2",
  TT: "usd_2",
  UY: "usd_2",
  VC: "usd_2",
  VE: "usd_2",
  VG: "usd_2",
  VU: "usd_2",
  YE: "usd_2",
  BH: "usd_3",
  BS: "usd_3",
  KG: "usd_3",
  KH: "usd_3",
  LA: "usd_3",
  SR: "usd_3",
  TJ: "usd_3",
  UZ: "usd_3",
  AL: "usd_4",
  AM: "usd_4",
  AZ: "usd_4",
  BB: "usd_4",
  BJ: "usd_4",
  BY: "usd_4",
  CI: "usd_4",
  CM: "usd_4",
  GE: "usd_4",
  GH: "usd_4",
  IS: "usd_4",
  KE: "usd_4",
  MD: "usd_4",
  MU: "usd_4",
  NP: "usd_4",
  SN: "usd_4",
  UA: "usd_4",
  UG: "usd_4",
  ZM: "usd_4",
  ZW: "usd_4",
  VN: "vnd",
  ZA: "zar",
} as const satisfies Record<string, keyof typeof REGIONAL_PRICING_MARKETS>;
export const REGIONAL_PRICING_COUNTRY_CODES = [
  "AE",
  "AF",
  "AG",
  "AI",
  "AL",
  "AM",
  "AO",
  "AR",
  "AT",
  "AU",
  "AZ",
  "BA",
  "BB",
  "BE",
  "BF",
  "BG",
  "BH",
  "BJ",
  "BM",
  "BN",
  "BO",
  "BR",
  "BS",
  "BT",
  "BW",
  "BY",
  "BZ",
  "CA",
  "CD",
  "CG",
  "CH",
  "CI",
  "CL",
  "CM",
  "CN",
  "CO",
  "CR",
  "CV",
  "CY",
  "CZ",
  "DE",
  "DK",
  "DM",
  "DO",
  "DZ",
  "EC",
  "EE",
  "EG",
  "ES",
  "FI",
  "FJ",
  "FM",
  "FR",
  "GA",
  "GB",
  "GD",
  "GE",
  "GH",
  "GM",
  "GR",
  "GT",
  "GW",
  "GY",
  "HK",
  "HN",
  "HR",
  "HU",
  "ID",
  "IE",
  "IL",
  "IN",
  "IQ",
  "IS",
  "IT",
  "JM",
  "JO",
  "JP",
  "KE",
  "KG",
  "KH",
  "KN",
  "KR",
  "KW",
  "KY",
  "KZ",
  "LA",
  "LB",
  "LC",
  "LK",
  "LR",
  "LT",
  "LU",
  "LV",
  "LY",
  "MA",
  "MD",
  "ME",
  "MG",
  "MK",
  "ML",
  "MM",
  "MN",
  "MO",
  "MR",
  "MS",
  "MT",
  "MU",
  "MV",
  "MW",
  "MX",
  "MY",
  "MZ",
  "NA",
  "NE",
  "NG",
  "NI",
  "NL",
  "NO",
  "NP",
  "NR",
  "NZ",
  "OM",
  "PA",
  "PE",
  "PG",
  "PH",
  "PK",
  "PL",
  "PT",
  "PW",
  "PY",
  "QA",
  "RO",
  "RS",
  "RU",
  "RW",
  "SA",
  "SB",
  "SC",
  "SE",
  "SG",
  "SI",
  "SK",
  "SL",
  "SN",
  "SR",
  "ST",
  "SV",
  "SZ",
  "TC",
  "TD",
  "TH",
  "TJ",
  "TM",
  "TN",
  "TO",
  "TR",
  "TT",
  "TW",
  "TZ",
  "UA",
  "UG",
  "US",
  "UY",
  "UZ",
  "VC",
  "VE",
  "VG",
  "VN",
  "VU",
  "XK",
  "YE",
  "ZA",
  "ZM",
  "ZW",
] as const;
export const REGIONAL_PRICING_CURRENCIES = [
  "AED",
  "AUD",
  "BRL",
  "CAD",
  "CHF",
  "CLP",
  "CNY",
  "COP",
  "CZK",
  "DKK",
  "EGP",
  "EUR",
  "GBP",
  "HKD",
  "HUF",
  "IDR",
  "ILS",
  "INR",
  "JPY",
  "KRW",
  "KZT",
  "MXN",
  "MYR",
  "NGN",
  "NOK",
  "NZD",
  "PEN",
  "PHP",
  "PKR",
  "PLN",
  "QAR",
  "RON",
  "RUB",
  "SAR",
  "SEK",
  "SGD",
  "THB",
  "TRY",
  "TWD",
  "TZS",
  "USD",
  "VND",
  "ZAR",
] as const;

export function isSupportedRegionalPricingCountry(
  countryCode: unknown,
): countryCode is keyof typeof REGIONAL_PRICING_COUNTRY_TO_MARKET {
  return (
    typeof countryCode === "string" &&
    countryCode.trim().toUpperCase() in REGIONAL_PRICING_COUNTRY_TO_MARKET
  );
}

export function getRegionalPricingMarket(
  countryCode?: string | null,
): RegionalPricingMarket {
  const normalizedCountry = countryCode?.trim().toUpperCase() ?? "";
  const marketId =
    REGIONAL_PRICING_COUNTRY_TO_MARKET[
      normalizedCountry as keyof typeof REGIONAL_PRICING_COUNTRY_TO_MARKET
    ] ?? DEFAULT_REGIONAL_PRICING_MARKET_ID;
  return REGIONAL_PRICING_MARKETS[marketId];
}

export function getRegionalStripePriceLookupKey(
  planTarget: string,
  catalogVersion: number = REGIONAL_PRICING_CATALOG_VERSION,
): string {
  return `moneko_${planTarget}_v${catalogVersion}`;
}

export function isSupportedRegionalCurrency(
  currencyCode: unknown,
): currencyCode is (typeof REGIONAL_PRICING_CURRENCIES)[number] {
  return (
    typeof currencyCode === "string" &&
    (REGIONAL_PRICING_CURRENCIES as readonly string[]).includes(
      currencyCode.trim().toUpperCase(),
    )
  );
}
