import { serve } from "https://deno.land/std@0.177.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.4";
import Stripe from "https://esm.sh/stripe@13.10.0";
import { getCorsHeaders } from "../shared/cors.ts";
import { validate as validateUuid } from "https://deno.land/std@0.177.0/uuid/mod.ts";
import { reportEdgeFunctionError } from "../shared/edge-error-alert.ts";
import {
  allowZeroAmountLifetimeGrants,
  isPositiveStripeAmount,
} from "../shared/lifetime-grant-policy.ts";
import { resolveInvoicePlanFromLinePrices } from "../shared/stripe-subscription-prices.ts";
import {
  buildPaymentVerificationResult,
  resolveRecurringPaymentEntitlement,
} from "../shared/verify-payment-entitlement.ts";

const stripeSecretKey = Deno.env.get("STRIPE_SECRET_KEY") || "";
const supabaseUrl = Deno.env.get("SUPABASE_URL") || "";
const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "";
if (!stripeSecretKey || !supabaseUrl || !supabaseKey) {
  throw new Error(
    "Missing required STRIPE_SECRET_KEY / SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY",
  );
}

// Initialize Stripe with account default API version.
// Keep this consistent with other Stripe edge functions in this repo.
const stripe = new Stripe(stripeSecretKey, {
  httpClient: Stripe.createFetchHttpClient(),
});

const supabase = createClient(supabaseUrl, supabaseKey);

function reportVerifyPaymentError(
  phase: string,
  error: unknown,
  context?: Record<string, unknown>,
): void {
  void reportEdgeFunctionError({
    functionName: "verify-payment",
    error,
    context: {
      phase,
      ...context,
    },
  });
}

type VerifyPaymentResponse = {
  verified: boolean;
  message?: string;
  subscription?: {
    provider: "stripe" | "app_store" | "play_store";
    plan: string;
    status: string;
    billing_interval: string | null;
    current_period_end: string | null;
    cancel_at_period_end: boolean;
    trial_end: string | null;
    stripe_subscription_id: string | null;
    stripe_customer_id: string | null;
  };
};

/**
 * Safely converts a Unix timestamp to ISO string
 * Returns null if timestamp is invalid or null
 */
function safeUnixToISO(
  unixTimestamp: number | null | undefined,
): string | null {
  if (!unixTimestamp) return null;

  try {
    const date = new Date(unixTimestamp * 1000);
    if (isNaN(date.getTime())) {
      console.warn("Invalid Unix timestamp:", unixTimestamp);
      return null;
    }
    return date.toISOString();
  } catch (error) {
    console.error("Error converting timestamp to ISO:", error);
    return null;
  }
}

function getStripeCustomerId(session: Stripe.Checkout.Session): string | null {
  const customer = session.customer as unknown;
  if (typeof customer === "string" && customer) return customer;
  if (
    customer &&
    typeof customer === "object" &&
    "id" in customer &&
    typeof (customer as any).id === "string"
  ) {
    return (customer as any).id;
  }
  return null;
}

serve(async (req: Request) => {
  const origin = req.headers.get("origin") || "";
  const corsHeaders = getCorsHeaders(origin);

  try {
    // Handle CORS preflight OPTIONS request
    if (req.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: corsHeaders });
    }

    // Only allow POST requests
    if (req.method !== "POST") {
      return new Response(JSON.stringify({ error: "Method not allowed" }), {
        status: 405,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const body = (await req.json().catch(() => null)) as {
      sessionId?: unknown;
      v?: unknown;
    } | null;

    const sessionId = typeof body?.sessionId === "string"
      ? body.sessionId
      : null;
    const v = typeof body?.v === "string" ? body.v : null;

    // verify-payment is deployed publicly (--no-verify-jwt) to support logged-out users.
    // The effective gate is the unguessable Stripe Checkout Session ID.

    // If caller is logged out, we require the per-session nonce generated by create-checkout-session.
    // If caller is logged in (valid JWT), only allow verifying their own session.
    const SUPABASE_ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY") || "";
    const authHeader = req.headers.get("Authorization") || "";
    let callerUserId: string | null = null;
    let expectedUserIdFromVerification: string | null = null;
    if (SUPABASE_ANON_KEY && authHeader) {
      try {
        const supabaseAuthed = createClient(supabaseUrl, SUPABASE_ANON_KEY, {
          auth: {
            autoRefreshToken: false,
            persistSession: false,
            detectSessionInUrl: false,
          },
          global: {
            headers: { Authorization: authHeader },
          },
        });

        const { data, error } = await supabaseAuthed.auth.getUser();
        if (!error) {
          callerUserId = data.user?.id ?? null;
        }
      } catch {
        // Ignore auth parse failures; treat as logged out.
      }
    }

    // Validate session ID
    if (!sessionId) {
      return new Response(JSON.stringify({ error: "Session ID is required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    if (
      typeof sessionId !== "string" ||
      !sessionId.startsWith("cs_") ||
      sessionId.length < 20
    ) {
      return new Response(JSON.stringify({ error: "Invalid session ID" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    if (!callerUserId) {
      if (!v || v.length < 16) {
        return new Response(
          JSON.stringify({ error: "Verification token required" }),
          {
            status: 401,
            headers: { ...corsHeaders, "Content-Type": "application/json" },
          },
        );
      }

      const { data: verificationRow, error: verificationError } = await supabase
        .from("stripe_checkout_session_verifications")
        .select("user_id, nonce, call_count")
        .eq("session_id", sessionId)
        .maybeSingle();

      if (verificationError) {
        reportVerifyPaymentError(
          "lookup_verification_session",
          verificationError,
          {
            sessionId,
            callerUserId,
          },
        );
        return new Response(
          JSON.stringify({ error: "Verification temporarily unavailable" }),
          {
            status: 503,
            headers: { ...corsHeaders, "Content-Type": "application/json" },
          },
        );
      }

      if (!verificationRow) {
        return new Response(
          JSON.stringify({ error: "Verification session not found" }),
          {
            status: 401,
            headers: { ...corsHeaders, "Content-Type": "application/json" },
          },
        );
      }

      if (verificationRow.nonce !== v) {
        return new Response(
          JSON.stringify({ error: "Invalid verification token" }),
          {
            status: 401,
            headers: { ...corsHeaders, "Content-Type": "application/json" },
          },
        );
      }

      // Lightweight abuse mitigation: track calls.
      // We don't block here, but we record usage for later throttling/monitoring.
      try {
        const { error: verificationUpdateError } = await supabase
          .from("stripe_checkout_session_verifications")
          .update({
            last_called_at: new Date().toISOString(),
            call_count: (verificationRow.call_count ?? 0) + 1,
          })
          .eq("session_id", sessionId);

        if (verificationUpdateError) {
          reportVerifyPaymentError(
            "update_verification_session_usage",
            verificationUpdateError,
            {
              sessionId,
              callerUserId,
            },
          );
        }
      } catch (error) {
        reportVerifyPaymentError("update_verification_session_usage", error, {
          sessionId,
          callerUserId,
        });
      }

      expectedUserIdFromVerification =
        typeof verificationRow.user_id === "string"
          ? verificationRow.user_id
          : null;
    }

    console.log("Verifying payment session:", sessionId);

    // Retrieve the session from Stripe
    const session = await stripe.checkout.sessions.retrieve(sessionId);

    const paymentStatus = session.payment_status;
    const isPaymentSuccess = paymentStatus === "paid" ||
      paymentStatus === "no_payment_required";

    // Check if the payment was successful
    if (!isPaymentSuccess) {
      console.log("Payment not successful:", paymentStatus);
      return new Response(
        JSON.stringify({
          verified: false,
          message: `Payment status is ${paymentStatus}`,
        }),
        {
          status: 200,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        },
      );
    }

    // Get the user ID from the session
    const userId = session.client_reference_id;

    // Validate that userId is a valid UUID
    if (!userId || !validateUuid(userId)) {
      console.error("Invalid or missing user ID:", userId);
      return new Response(
        JSON.stringify({
          verified: false,
          message: "Invalid or missing user ID",
        }),
        {
          status: 200,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        },
      );
    }

    if (!callerUserId && expectedUserIdFromVerification) {
      if (expectedUserIdFromVerification !== userId) {
        return new Response(JSON.stringify({ error: "Forbidden" }), {
          status: 403,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
    }

    // If caller is authenticated, require they are verifying their own checkout session.
    if (callerUserId && callerUserId !== userId) {
      return new Response(JSON.stringify({ error: "Forbidden" }), {
        status: 403,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Handle Lifetime (mode='payment') vs Recurring (mode='subscription') sessions
    const subscriptionId = session.subscription as string;

    // Lifetime plan: one-time payment (mode='payment'), no subscription ID
    if (session.mode === "payment") {
      console.log("Lifetime payment session detected - fulfilling immediately");

      if (paymentStatus !== "paid") {
        return new Response(
          JSON.stringify({
            verified: false,
            message: `Payment status is ${paymentStatus}`,
          }),
          {
            status: 200,
            headers: { ...corsHeaders, "Content-Type": "application/json" },
          },
        );
      }

      if (
        !isPositiveStripeAmount(session.amount_total) &&
        !allowZeroAmountLifetimeGrants()
      ) {
        return new Response(
          JSON.stringify({
            verified: false,
            message: "Lifetime payment amount could not be verified",
          }),
          {
            status: 200,
            headers: { ...corsHeaders, "Content-Type": "application/json" },
          },
        );
      }

      const lineItems = await stripe.checkout.sessions.listLineItems(
        sessionId,
        { limit: 100 },
      );
      const linePlanInfo = resolveInvoicePlanFromLinePrices({
        lines: lineItems as any,
      });

      if (linePlanInfo?.plan !== "lifetime") {
        return new Response(
          JSON.stringify({
            verified: false,
            message: "Lifetime price could not be verified",
          }),
          {
            status: 200,
            headers: { ...corsHeaders, "Content-Type": "application/json" },
          },
        );
      }

      const plan = "lifetime";

      // A completed historical checkout must never change the provenance of an
      // already-active Lifetime grant. This also makes repeated verification
      // idempotent when the current grant came from Apple or an administrator.
      const { data: currentEntitlement, error: currentEntitlementError } =
        await supabase
          .from("subscriptions")
          .select("*")
          .eq("user_id", userId)
          .maybeSingle();
      if (currentEntitlementError) {
        await reportEdgeFunctionError({
          functionName: "verify-payment",
          error: currentEntitlementError,
          context: {
            phase: "load_current_lifetime_entitlement",
            userId,
            sessionId,
          },
        });
        console.error(
          "Failed to load current entitlement before Lifetime verification:",
          currentEntitlementError,
        );
        return new Response(
          JSON.stringify(
            {
              verified: false,
              message: "Failed to verify current entitlement",
            } satisfies VerifyPaymentResponse,
          ),
          {
            status: 200,
            headers: { ...corsHeaders, "Content-Type": "application/json" },
          },
        );
      }
      if (
        currentEntitlement?.plan === "lifetime" &&
        currentEntitlement?.status === "active"
      ) {
        const incomingPaymentIntentId =
          typeof session.payment_intent === "string"
            ? session.payment_intent
            : session.payment_intent?.id ?? null;
        const isSameLifetimeGrant =
          currentEntitlement.lifetime_source === "stripe" &&
          incomingPaymentIntentId !== null &&
          currentEntitlement.lifetime_source_id === incomingPaymentIntentId;
        if (!isSameLifetimeGrant) {
          await reportEdgeFunctionError({
            functionName: "verify-payment",
            error: new Error(
              "Verified Stripe Lifetime purchase cannot be represented alongside the current active Lifetime grant",
            ),
            context: {
              phase: "multiple_active_lifetime_grants_detected",
              userId,
              sessionId,
              currentLifetimeSource: currentEntitlement.lifetime_source ?? null,
              incomingLifetimeSource: "stripe",
            },
          });
        }
        return new Response(
          JSON.stringify(
            {
              verified: true,
              message: "Lifetime payment successful",
              subscription: currentEntitlement,
            } satisfies VerifyPaymentResponse,
          ),
          {
            status: 200,
            headers: { ...corsHeaders, "Content-Type": "application/json" },
          },
        );
      }

      let persistenceError: unknown = null;
      let stripeCustomerId: string | null = null;

      // Idempotent DB upsert so mobile deep-link callback can unlock immediately.
      // The callback must still fail closed if entitlement persistence fails.
      try {
        const now = new Date();
        stripeCustomerId = getStripeCustomerId(session);

        const subscriptionData = {
          user_id: userId,
          provider: "stripe",
          stripe_subscription_id: null,
          stripe_customer_id: stripeCustomerId,
          // Provider hygiene: prevent mixed-source subscription rows.
          store_product_id: null,
          app_store_transaction_id: null,
          app_store_original_transaction_id: null,
          app_store_environment: null,
          play_purchase_token: null,
          play_order_id: null,
          play_package_name: null,
          plan,
          status: "active",
          billing_interval: null,
          current_period_end: null, // Lifetime must have NULL period end
          cancel_at_period_end: false,
          bound_to_user_id: null,
          bound_to_household_id: null,
          trial_start: null,
          trial_end: null,
          lifetime_source: "stripe",
          lifetime_source_id: typeof session.payment_intent === "string"
            ? session.payment_intent
            : session.payment_intent?.id ?? `checkout:${sessionId}`,
          updated_at: now.toISOString(),
        };

        const { error: upsertError } = await supabase
          .from("subscriptions")
          .upsert(subscriptionData, { onConflict: "user_id" });

        if (upsertError) {
          persistenceError = upsertError;
          await reportEdgeFunctionError({
            functionName: "verify-payment",
            error: upsertError,
            context: {
              phase: "persist_lifetime_entitlement",
              userId,
              sessionId,
            },
          });
          console.error("Failed to upsert lifetime subscription:", upsertError);
        } else {
          console.log("Lifetime subscription upserted for user:", userId);
        }
      } catch (dbError) {
        persistenceError = dbError;
        await reportEdgeFunctionError({
          functionName: "verify-payment",
          error: dbError,
          context: {
            phase: "persist_lifetime_entitlement_unexpected",
            userId,
            sessionId,
          },
        });
        console.error("Failed to upsert lifetime subscription:", dbError);
      }

      const result = buildPaymentVerificationResult({
        persistenceError,
        success: {
          verified: true,
          message: "Lifetime payment successful",
          subscription: {
            provider: "stripe",
            plan,
            status: "active",
            billing_interval: null,
            current_period_end: null,
            cancel_at_period_end: false,
            trial_end: null,
            stripe_subscription_id: null,
            stripe_customer_id: stripeCustomerId,
          },
        },
      });

      return new Response(
        JSON.stringify(result satisfies VerifyPaymentResponse),
        {
          status: 200,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        },
      );
    }

    // Recurring plans: require subscription ID
    if (!subscriptionId) {
      console.error("No subscription ID found in session");
      return new Response(
        JSON.stringify({
          verified: false,
          message: "No subscription found",
        }),
        {
          status: 200,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        },
      );
    }

    // Retrieve the subscription from Stripe
    const subscription = await stripe.subscriptions.retrieve(subscriptionId);

    const entitlement = resolveRecurringPaymentEntitlement(subscription);
    if (!entitlement.verified) {
      return new Response(
        JSON.stringify(
          {
            verified: false,
            message: entitlement.message,
          } satisfies VerifyPaymentResponse,
        ),
        {
          status: 200,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        },
      );
    }

    // Extract subscription details with proper null handling
    const plan = entitlement.plan;
    const status = subscription.status;

    // CRITICAL: For trialing subscriptions without payment method, use trial_end as current_period_end
    // This ensures every subscription has a proper end date (30 days default)
    let currentPeriodEnd = safeUnixToISO(subscription.current_period_end);
    const trialEnd = safeUnixToISO(subscription.trial_end);

    // If subscription is trialing without payment method, use trial_end as the period end
    if (!currentPeriodEnd && status === "trialing" && trialEnd) {
      console.log(
        "Trialing subscription without payment method - using trial_end as current_period_end",
      );
      currentPeriodEnd = trialEnd;
    } else if (!currentPeriodEnd && subscription.current_period_end) {
      console.warn(
        "Failed to convert current_period_end:",
        subscription.current_period_end,
      );
    } else if (!currentPeriodEnd) {
      console.warn(
        "Subscription has no current_period_end or trial_end - this may cause issues",
      );
    }

    const cancelAtPeriodEnd = subscription.cancel_at_period_end;

    const billingInterval = entitlement.billingInterval;

    console.log("Subscription details:", {
      id: subscriptionId,
      plan,
      status,
      currentPeriodEnd,
      trialEnd,
      cancelAtPeriodEnd,
      hasPaymentMethod: !!subscription.default_payment_method,
    });

    // Update the user's subscription in the database
    // userId is already validated as a valid UUID
    let persistenceError: unknown = null;
    const stripeCustomerId = getStripeCustomerId(session);
    try {
      const now = new Date();

      const subscriptionData = {
        user_id: userId,
        provider: "stripe",
        stripe_subscription_id: subscriptionId,
        stripe_customer_id: stripeCustomerId,
        // Provider hygiene: prevent mixed-source subscription rows.
        store_product_id: null,
        app_store_transaction_id: null,
        app_store_original_transaction_id: null,
        app_store_environment: null,
        play_purchase_token: null,
        play_order_id: null,
        play_package_name: null,
        bound_to_user_id: null,
        bound_to_household_id: null,
        plan,
        status,
        billing_interval: billingInterval,
        current_period_end: currentPeriodEnd,
        cancel_at_period_end: cancelAtPeriodEnd,
        trial_start: safeUnixToISO(subscription.trial_start),
        trial_end: trialEnd,
        updated_at: now.toISOString(),
      };

      const { error: upsertError } = await supabase
        .from("subscriptions")
        .upsert(subscriptionData, { onConflict: "user_id" });

      if (upsertError) {
        persistenceError = upsertError;
        await reportEdgeFunctionError({
          functionName: "verify-payment",
          error: upsertError,
          context: {
            phase: "persist_recurring_entitlement",
            userId,
            sessionId,
            subscriptionId,
          },
        });
        console.error("Error upserting subscription:", upsertError);
      }
    } catch (dbError) {
      persistenceError = dbError;
      await reportEdgeFunctionError({
        functionName: "verify-payment",
        error: dbError,
        context: {
          phase: "persist_recurring_entitlement_unexpected",
          userId,
          sessionId,
          subscriptionId,
        },
      });
      console.error("Database error:", dbError);
    }

    const result = buildPaymentVerificationResult({
      persistenceError,
      success: {
        verified: true,
        subscription: {
          provider: "stripe",
          plan,
          status,
          billing_interval: billingInterval,
          current_period_end: currentPeriodEnd || null,
          cancel_at_period_end: cancelAtPeriodEnd,
          trial_end: trialEnd,
          stripe_subscription_id: subscriptionId,
          stripe_customer_id: stripeCustomerId,
        },
      },
    });

    // Return success response with subscription details
    return new Response(
      JSON.stringify(result satisfies VerifyPaymentResponse),
      {
        status: 200,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      },
    );
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    await reportEdgeFunctionError({
      functionName: "verify-payment",
      error,
      context: {
        phase: "serve_handler",
      },
    });
    console.error("Error verifying payment:", error);
    return new Response(JSON.stringify({ error: message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
