// Map timezones to ISO country codes for flag display
export function getCountryCodeFromTimezone(timezone: string): string | null {
  const mapping: Record<string, string> = {
    "America/New_York": "US",
    "America/Chicago": "US",
    "America/Denver": "US",
    "America/Los_Angeles": "US",
    "America/Phoenix": "US",
    "America/Anchorage": "US",
    "America/Honolulu": "US",
    "America/Toronto": "CA",
    "America/Vancouver": "CA",
    "America/Montreal": "CA",
    "America/Edmonton": "CA",
    "America/Winnipeg": "CA",
    "America/Halifax": "CA",
    "Europe/London": "GB",
    "Europe/Paris": "FR",
    "Europe/Berlin": "DE",
    "Europe/Madrid": "ES",
    "Europe/Rome": "IT",
    "Europe/Amsterdam": "NL",
    "Europe/Brussels": "BE",
    "Europe/Vienna": "AT",
    "Europe/Zurich": "CH",
    "Europe/Stockholm": "SE",
    "Europe/Oslo": "NO",
    "Europe/Copenhagen": "DK",
    "Europe/Helsinki": "FI",
    "Europe/Dublin": "IE",
    "Europe/Lisbon": "PT",
    "Europe/Prague": "CZ",
    "Europe/Warsaw": "PL",
    "Europe/Budapest": "HU",
    "Europe/Bucharest": "RO",
    "Europe/Sofia": "BG",
    "Europe/Athens": "GR",
    "Europe/Istanbul": "TR",
    "Europe/Moscow": "RU",
    "Europe/Kiev": "UA",
    "Europe/Minsk": "BY",
    "Asia/Tokyo": "JP",
    "Asia/Shanghai": "CN",
    "Asia/Beijing": "CN",
    "Asia/Hong_Kong": "HK",
    "Asia/Singapore": "SG",
    "Asia/Seoul": "KR",
    "Asia/Taipei": "TW",
    "Asia/Bangkok": "TH",
    "Asia/Jakarta": "ID",
    "Asia/Manila": "PH",
    "Asia/Kuala_Lumpur": "MY",
    "Asia/Hanoi": "VN",
    "Asia/Dubai": "AE",
    "Asia/Riyadh": "SA",
    "Asia/Tehran": "IR",
    "Asia/Karachi": "PK",
    "Asia/Mumbai": "IN",
    "Asia/Delhi": "IN",
    "Asia/Kolkata": "IN",
    "Asia/Bangalore": "IN",
    "Asia/Chennai": "IN",
    "Asia/Hyderabad": "IN",
    "Asia/Dhaka": "BD",
    "Asia/Colombo": "LK",
    "Asia/Kathmandu": "NP",
    "Asia/Thimphu": "BT",
    "Asia/Male": "MV",
    "Asia/Kabul": "AF",
    "Asia/Tashkent": "UZ",
    "Asia/Almaty": "KZ",
    "Asia/Ashgabat": "TM",
    "Asia/Baku": "AZ",
    "Asia/Tbilisi": "GE",
    "Asia/Yerevan": "AM",
    "Australia/Sydney": "AU",
    "Australia/Melbourne": "AU",
    "Australia/Brisbane": "AU",
    "Australia/Perth": "AU",
    "Australia/Adelaide": "AU",
    "Australia/Darwin": "AU",
    "Australia/Hobart": "AU",
    "Pacific/Auckland": "NZ",
    "Pacific/Fiji": "FJ",
    "Pacific/Guam": "GU",
    "Pacific/Honolulu": "US",
    "Africa/Cairo": "EG",
    "Africa/Johannesburg": "ZA",
    "Africa/Lagos": "NG",
    "Africa/Nairobi": "KE",
    "Africa/Addis_Ababa": "ET",
    "Africa/Accra": "GH",
    "Africa/Dakar": "SN",
    "Africa/Casablanca": "MA",
    "Africa/Tunis": "TN",
    "Africa/Algiers": "DZ",
    "Africa/Khartoum": "SD",
    "Africa/Kampala": "UG",
    "Africa/Dar_es_Salaam": "TZ",
    "Africa/Kigali": "RW",
    "Africa/Lusaka": "ZM",
    "Africa/Harare": "ZW",
    "Africa/Maputo": "MZ",
    "Africa/Luanda": "AO",
    "Africa/Libreville": "GA",
    "Africa/Malabo": "GQ",
    "Africa/Niamey": "NE",
    "Africa/Nouakchott": "MR",
    "Africa/Bamako": "ML",
    "Africa/Ouagadougou": "BF",
    "Africa/Porto-Novo": "BJ",
    "Africa/Lome": "TG",
    "Africa/Yaounde": "CM",
    "Africa/Bangui": "CF",
    "Africa/N'Djamena": "TD",
    "Africa/Brazzaville": "CG",
    "Africa/Kinshasa": "CD",
    "Africa/Lubumbashi": "CD",
    "Africa/Bujumbura": "BI",
    "Africa/Mogadishu": "SO",
    "Africa/Juba": "SS",
    "Africa/Bangkok": "TH",
    "America/Mexico_City": "MX",
    "America/Guadalajara": "MX",
    "America/Monterrey": "MX",
    "America/Tijuana": "MX",
    "America/Cancun": "MX",
    "America/Merida": "MX",
    "America/Ojinaga": "MX",
    "America/Chihuahua": "MX",
    "America/Hermosillo": "MX",
    "America/Mazatlan": "MX",
    "America/Bahia_Banderas": "MX",
    "America/Sao_Paulo": "BR",
    "America/Rio_de_Janeiro": "BR",
    "America/Buenos_Aires": "AR",
    "America/Santiago": "CL",
    "America/Lima": "PE",
    "America/Bogota": "CO",
    "America/Caracas": "VE",
    "America/Quito": "EC",
    "America/La_Paz": "BO",
    "America/Asuncion": "PY",
    "America/Montevideo": "UY",
    "America/Guyana": "GY",
    "America/Suriname": "SR",
    "America/Cayenne": "GF",
    "America/Panama": "PA",
    "America/Costa_Rica": "CR",
    "America/Guatemala": "GT",
    "America/Tegucigalpa": "HN",
    "America/Managua": "NI",
    "America/San_Salvador": "SV",
    "America/Belize": "BZ",
    "America/Jamaica": "JM",
    "America/Havana": "CU",
    "America/Port-au-Prince": "HT",
    "America/Santo_Domingo": "DO",
    "America/Puerto_Rico": "PR",
    "America/Barbados": "BB",
    "America/Trinidad": "TT",
    "America/Guadeloupe": "GP",
    "America/Martinique": "MQ",
    "America/St_Lucia": "LC",
    "America/St_Vincent": "VC",
    "America/Grenada": "GD",
    "America/Dominica": "DM",
    "America/Antigua": "AG",
    "America/St_Kitts": "KN",
    "America/Montserrat": "MS",
    "America/Anguilla": "AI",
    "America/Tortola": "VG",
    "America/St_Thomas": "VI",
    "America/Cayman": "KY",
    "America/Turks": "TC",
    "America/Grand_Turk": "TC",
    "America/Argentina/Buenos_Aires": "AR",
    "America/Argentina/Cordoba": "AR",
    "America/Argentina/Salta": "AR",
    "America/Argentina/Jujuy": "AR",
    "America/Argentina/Tucuman": "AR",
    "America/Argentina/Catamarca": "AR",
    "America/Argentina/La_Rioja": "AR",
    "America/Argentina/San_Juan": "AR",
    "America/Argentina/Mendoza": "AR",
    "America/Argentina/San_Luis": "AR",
    "America/Argentina/Rio_Gallegos": "AR",
    "America/Argentina/Ushuaia": "AR",
    "America/Kentucky/Louisville": "US",
    "America/Kentucky/Monticello": "US",
    "America/Indiana/Indianapolis": "US",
    "America/Indiana/Vincennes": "US",
    "America/Indiana/Winamac": "US",
    "America/Indiana/Marengo": "US",
    "America/Indiana/Petersburg": "US",
    "America/Indiana/Vevay": "US",
    "America/Indiana/Tell_City": "US",
    "America/Indiana/Knox": "US",
    "America/North_Dakota/Center": "US",
    "America/North_Dakota/New_Salem": "US",
    "America/North_Dakota/Beulah": "US",
  };

  return mapping[timezone] || null;
}

// Generate FlagCDN URL for a country code
export function getFlagUrl(countryCode: string, size: number = 24): string {
  return `https://flagcdn.com/${size}x${size}/${countryCode.toLowerCase()}.png`;
}

// Approximate timezone coordinates for map display
export function getTimezoneCoordinates(timezone: string): { x: number; y: number } | null {
  const coords: Record<string, { x: number; y: number }> = {
    "America/New_York": { x: 22, y: 35 },
    "America/Chicago": { x: 20, y: 36 },
    "America/Denver": { x: 18, y: 37 },
    "America/Los_Angeles": { x: 15, y: 38 },
    "America/Toronto": { x: 23, y: 33 },
    "America/Vancouver": { x: 16, y: 30 },
    "Europe/London": { x: 48, y: 32 },
    "Europe/Paris": { x: 50, y: 33 },
    "Europe/Berlin": { x: 52, y: 32 },
    "Europe/Madrid": { x: 47, y: 38 },
    "Europe/Rome": { x: 53, y: 36 },
    "Asia/Tokyo": { x: 85, y: 38 },
    "Asia/Shanghai": { x: 78, y: 42 },
    "Asia/Hong_Kong": { x: 76, y: 48 },
    "Asia/Singapore": { x: 74, y: 55 },
    "Asia/Seoul": { x: 82, y: 38 },
    "Asia/Taipei": { x: 79, y: 45 },
    "Asia/Bangkok": { x: 72, y: 50 },
    "Asia/Jakarta": { x: 75, y: 62 },
    "Asia/Manila": { x: 80, y: 50 },
    "Asia/Kuala_Lumpur": { x: 74, y: 55 },
    "Asia/Dubai": { x: 60, y: 48 },
    "Asia/Riyadh": { x: 58, y: 46 },
    "Asia/Mumbai": { x: 65, y: 52 },
    "Asia/Delhi": { x: 66, y: 48 },
    "Asia/Kolkata": { x: 70, y: 50 },
    "Asia/Bangalore": { x: 67, y: 55 },
    "Asia/Hyderabad": { x: 68, y: 54 },
    "Australia/Sydney": { x: 88, y: 75 },
    "Australia/Melbourne": { x: 85, y: 78 },
    "Australia/Brisbane": { x: 90, y: 70 },
    "Australia/Perth": { x: 80, y: 72 },
    "Pacific/Auckland": { x: 95, y: 80 },
    "Africa/Cairo": { x: 55, y: 48 },
    "Africa/Johannesburg": { x: 54, y: 75 },
    "Africa/Lagos": { x: 50, y: 55 },
    "Africa/Nairobi": { x: 60, y: 60 },
    "America/Sao_Paulo": { x: 32, y: 70 },
    "America/Rio_de_Janeiro": { x: 34, y: 72 },
    "America/Buenos_Aires": { x: 30, y: 80 },
    "America/Santiago": { x: 28, y: 78 },
    "America/Lima": { x: 25, y: 65 },
    "America/Bogota": { x: 26, y: 58 },
    "America/Caracas": { x: 28, y: 55 },
    "America/Mexico_City": { x: 20, y: 50 },
  };

  // Try exact match first
  if (coords[timezone]) {
    return coords[timezone];
  }

  // Try region prefix match
  const region = timezone.split("/")[0];
  const regionCoords: Record<string, { x: number; y: number }> = {
    "America": { x: 25, y: 45 },
    "Europe": { x: 50, y: 35 },
    "Asia": { x: 70, y: 45 },
    "Australia": { x: 85, y: 72 },
    "Pacific": { x: 90, y: 60 },
    "Africa": { x: 55, y: 60 },
    "Atlantic": { x: 45, y: 40 },
    "Indian": { x: 65, y: 60 },
    "Antarctica": { x: 50, y: 90 },
    "Arctic": { x: 50, y: 10 },
    "US": { x: 22, y: 38 },
  };

  return regionCoords[region] || { x: 50, y: 50 };
}
