/**
 * Preset financial profiles for quick quiz completion
 * These profiles represent common financial situations across different demographics
 */

export interface PresetProfile {
  id: string;
  name: string;
  description: string;
  icon: string;
  ageRange: string;
  answers: Record<string, string | string[] | number | boolean | any[]>;
}

export const presetProfiles: PresetProfile[] = [
  {
    id: 'undergraduate-student',
    name: 'College Student',
    description: 'Undergraduate with part-time job, minimal expenses',
    icon: '🎓',
    ageRange: '18-22',
    answers: {
      current_age: 20,
      dependents: 0,
      marital_status: 'single',
      gross_monthly_income: 800,
      net_monthly_income: 750,
      income_stability: 'somewhat_unstable',
      additional_income_sources: ['freelance_work'],
      annual_bonus: 0,
      housing_cost: 400,
      housing_type: 'living_with_family',
      food_expenses: 150,
      transportation_expenses: 50,
      healthcare_expenses: 20,
      insurance_expenses: 0,
      entertainment_expenses: 100,
      other_monthly_expenses: 30,
      emergency_fund: 500,
      checking_account: 300,
      savings_account: 1000,
      investment_accounts: 0,
      retirement_accounts: 0,
      real_estate_value: 0,
      other_assets: 0,
      credit_card_debt: 500,
      credit_card_interest_rate: 22,
      student_loan_debt: 10000,
      student_loan_interest_rate: 4.5,
      mortgage_balance: 0,
      mortgage_interest_rate: 0,
      auto_loan_balance: 0,
      auto_loan_interest_rate: 0,
      other_debt: 0,
      other_debt_interest_rate: 0,
      retirement_age: 67,
      desired_retirement_income: 5000,
      short_term_goals: ['vacation', 'debt_payoff'],
      medium_term_goals: [],
      long_term_goals: ['comfortable_retirement'],
      major_purchase_timeline: 'Car in 3 years',
      risk_tolerance: 'aggressive',
      investment_experience: 'none',
      investment_timeline: 'long',
      investment_priorities: ['growth'],
      savings_rate: 5,
      spending_tracking: 'occasionally',
      budget_adherence: 'sometimes',
      financial_stress_level: 6,
    }
  },
  {
    id: 'recent-graduate',
    name: 'Recent Graduate',
    description: 'Just entered workforce, student loans, starting salary',
    icon: '👨‍💼',
    ageRange: '22-25',
    answers: {
      current_age: 24,
      dependents: 0,
      marital_status: 'single',
      gross_monthly_income: 4500,
      net_monthly_income: 3600,
      income_stability: 'stable',
      additional_income_sources: [],
      annual_bonus: 2000,
      housing_cost: 1200,
      housing_type: 'rent',
      food_expenses: 400,
      transportation_expenses: 200,
      healthcare_expenses: 150,
      insurance_expenses: 100,
      entertainment_expenses: 300,
      other_monthly_expenses: 150,
      emergency_fund: 4000,
      checking_account: 1500,
      savings_account: 5000,
      investment_accounts: 1000,
      retirement_accounts: 5000,
      real_estate_value: 0,
      other_assets: 500,
      credit_card_debt: 2000,
      credit_card_interest_rate: 18,
      student_loan_debt: 35000,
      student_loan_interest_rate: 5.8,
      mortgage_balance: 0,
      mortgage_interest_rate: 0,
      auto_loan_balance: 0,
      auto_loan_interest_rate: 0,
      other_debt: 0,
      other_debt_interest_rate: 0,
      retirement_age: 65,
      desired_retirement_income: 6000,
      short_term_goals: ['emergency_fund', 'debt_payoff'],
      medium_term_goals: ['home_purchase'],
      long_term_goals: ['comfortable_retirement'],
      major_purchase_timeline: 'Home in 5-7 years',
      risk_tolerance: 'aggressive',
      investment_experience: 'beginner',
      investment_timeline: 'long',
      investment_priorities: ['growth', 'diversification'],
      savings_rate: 15,
      spending_tracking: 'monthly',
      budget_adherence: 'usually',
      financial_stress_level: 7,
    }
  },
  {
    id: 'young-professional',
    name: 'Young Professional',
    description: 'Established career, no major debts, building savings',
    icon: '💼',
    ageRange: '25-32',
    answers: {
      current_age: 28,
      dependents: 0,
      marital_status: 'single',
      gross_monthly_income: 7500,
      net_monthly_income: 5800,
      income_stability: 'very_stable',
      additional_income_sources: [],
      annual_bonus: 10000,
      housing_cost: 1800,
      housing_type: 'rent',
      food_expenses: 500,
      transportation_expenses: 300,
      healthcare_expenses: 250,
      insurance_expenses: 150,
      entertainment_expenses: 500,
      other_monthly_expenses: 300,
      emergency_fund: 15000,
      checking_account: 3000,
      savings_account: 20000,
      investment_accounts: 25000,
      retirement_accounts: 40000,
      real_estate_value: 0,
      other_assets: 2000,
      credit_card_debt: 1000,
      credit_card_interest_rate: 15,
      student_loan_debt: 0,
      student_loan_interest_rate: 0,
      mortgage_balance: 0,
      mortgage_interest_rate: 0,
      auto_loan_balance: 15000,
      auto_loan_interest_rate: 4,
      other_debt: 0,
      other_debt_interest_rate: 0,
      retirement_age: 62,
      desired_retirement_income: 8000,
      short_term_goals: ['home_down_payment', 'vacation'],
      medium_term_goals: ['home_purchase', 'career_change'],
      long_term_goals: ['early_retirement'],
      major_purchase_timeline: 'Condo in 3 years',
      risk_tolerance: 'moderate',
      investment_experience: 'intermediate',
      investment_timeline: 'long',
      investment_priorities: ['growth', 'tax_efficiency'],
      savings_rate: 25,
      spending_tracking: 'weekly',
      budget_adherence: 'usually',
      financial_stress_level: 4,
    }
  },
  {
    id: 'young-family',
    name: 'Young Family',
    description: 'Married couple with children, mortgage, family expenses',
    icon: '👨‍👩‍👧‍👦',
    ageRange: '28-40',
    answers: {
      current_age: 35,
      dependents: 2,
      marital_status: 'married',
      gross_monthly_income: 12000,
      net_monthly_income: 9000,
      income_stability: 'stable',
      additional_income_sources: [],
      annual_bonus: 15000,
      housing_cost: 2500,
      housing_type: 'mortgage',
      food_expenses: 1000,
      transportation_expenses: 500,
      healthcare_expenses: 800,
      insurance_expenses: 400,
      entertainment_expenses: 600,
      other_monthly_expenses: 700, // (childcare, etc.)
      emergency_fund: 25000,
      checking_account: 5000,
      savings_account: 15000,
      investment_accounts: 30000, // (includes 529 plans)
      retirement_accounts: 120000,
      real_estate_value: 450000,
      other_assets: 10000,
      credit_card_debt: 4000,
      credit_card_interest_rate: 17,
      student_loan_debt: 20000,
      student_loan_interest_rate: 6,
      mortgage_balance: 300000,
      mortgage_interest_rate: 3.5,
      auto_loan_balance: 20000,
      auto_loan_interest_rate: 4.5,
      other_debt: 0,
      other_debt_interest_rate: 0,
      retirement_age: 65,
      desired_retirement_income: 10000,
      short_term_goals: ['debt_payoff'],
      medium_term_goals: ['children_education', 'major_renovation'],
      long_term_goals: ['comfortable_retirement'],
      major_purchase_timeline: 'None',
      risk_tolerance: 'moderate',
      investment_experience: 'intermediate',
      investment_timeline: 'long',
      investment_priorities: ['growth', 'diversification'],
      savings_rate: 15,
      spending_tracking: 'monthly',
      budget_adherence: 'usually',
      financial_stress_level: 8,
    }
  },
  {
    id: 'mid-career-debt',
    name: 'Mid-Career with Debt',
    description: 'Established income but multiple debts and obligations',
    icon: '📊',
    ageRange: '35-45',
    answers: {
      current_age: 40,
      dependents: 1,
      marital_status: 'married',
      gross_monthly_income: 9000,
      net_monthly_income: 6800,
      income_stability: 'stable',
      additional_income_sources: [],
      annual_bonus: 5000,
      housing_cost: 2000,
      housing_type: 'mortgage',
      food_expenses: 800,
      transportation_expenses: 400,
      healthcare_expenses: 500,
      insurance_expenses: 300,
      entertainment_expenses: 500,
      other_monthly_expenses: 300,
      emergency_fund: 5000,
      checking_account: 2000,
      savings_account: 3000,
      investment_accounts: 10000,
      retirement_accounts: 80000,
      real_estate_value: 350000,
      other_assets: 5000,
      credit_card_debt: 25000,
      credit_card_interest_rate: 24,
      student_loan_debt: 15000,
      student_loan_interest_rate: 5,
      mortgage_balance: 250000,
      mortgage_interest_rate: 4,
      auto_loan_balance: 10000,
      auto_loan_interest_rate: 5.5,
      other_debt: 5000,
      other_debt_interest_rate: 10,
      retirement_age: 67,
      desired_retirement_income: 7000,
      short_term_goals: ['debt_payoff', 'emergency_fund'],
      medium_term_goals: ['career_change'],
      long_term_goals: ['comfortable_retirement'],
      major_purchase_timeline: 'None',
      risk_tolerance: 'conservative',
      investment_experience: 'beginner',
      investment_timeline: 'medium',
      investment_priorities: ['stability'],
      savings_rate: 5,
      spending_tracking: 'occasionally',
      budget_adherence: 'sometimes',
      financial_stress_level: 9,
    }
  },
  {
    id: 'high-earner',
    name: 'Senior Executive',
    description: 'High income, complex investments, pre-retirement planning',
    icon: '👔',
    ageRange: '45-55',
    answers: {
      current_age: 50,
      dependents: 0,
      marital_status: 'married',
      gross_monthly_income: 25000,
      net_monthly_income: 18000,
      income_stability: 'very_stable',
      additional_income_sources: ['investment_dividends', 'rental_income'],
      annual_bonus: 100000,
      housing_cost: 4000,
      housing_type: 'mortgage',
      food_expenses: 1200,
      transportation_expenses: 800,
      healthcare_expenses: 1000,
      insurance_expenses: 800,
      entertainment_expenses: 2000,
      other_monthly_expenses: 1200,
      emergency_fund: 100000,
      checking_account: 20000,
      savings_account: 150000,
      investment_accounts: 800000,
      retirement_accounts: 1500000,
      real_estate_value: 1200000,
      other_assets: 250000,
      credit_card_debt: 0,
      credit_card_interest_rate: 0,
      student_loan_debt: 0,
      student_loan_interest_rate: 0,
      mortgage_balance: 400000,
      mortgage_interest_rate: 3,
      auto_loan_balance: 0,
      auto_loan_interest_rate: 0,
      other_debt: 0,
      other_debt_interest_rate: 0,
      retirement_age: 60,
      desired_retirement_income: 15000,
      short_term_goals: [],
      medium_term_goals: [],
      long_term_goals: ['early_retirement', 'legacy_wealth', 'charity_giving'],
      major_purchase_timeline: 'Vacation home in 2 years',
      risk_tolerance: 'moderate',
      investment_experience: 'advanced',
      investment_timeline: 'medium',
      investment_priorities: ['tax_efficiency', 'growth', 'stability'],
      savings_rate: 35,
      spending_tracking: 'monthly',
      budget_adherence: 'always',
      financial_stress_level: 3,
    }
  },
  {
    id: 'pre-retiree',
    name: 'Pre-Retiree',
    description: 'Approaching retirement, established wealth, conservative approach',
    icon: '🏡',
    ageRange: '55-65',
    answers: {
      current_age: 60,
      dependents: 0,
      marital_status: 'married',
      gross_monthly_income: 15000,
      net_monthly_income: 11000,
      income_stability: 'very_stable',
      additional_income_sources: ['investment_dividends'],
      annual_bonus: 25000,
      housing_cost: 1500, // (low mortgage or just taxes/insurance)
      housing_type: 'mortgage',
      food_expenses: 800,
      transportation_expenses: 400,
      healthcare_expenses: 1200,
      insurance_expenses: 600,
      entertainment_expenses: 1000,
      other_monthly_expenses: 500,
      emergency_fund: 75000,
      checking_account: 15000,
      savings_account: 100000,
      investment_accounts: 500000,
      retirement_accounts: 2000000,
      real_estate_value: 700000,
      other_assets: 50000,
      credit_card_debt: 0,
      credit_card_interest_rate: 0,
      student_loan_debt: 0,
      student_loan_interest_rate: 0,
      mortgage_balance: 50000,
      mortgage_interest_rate: 3.2,
      auto_loan_balance: 0,
      auto_loan_interest_rate: 0,
      other_debt: 0,
      other_debt_interest_rate: 0,
      retirement_age: 65,
      desired_retirement_income: 9000,
      short_term_goals: [],
      medium_term_goals: [],
      long_term_goals: ['comfortable_retirement', 'legacy_wealth'],
      major_purchase_timeline: 'None',
      risk_tolerance: 'conservative',
      investment_experience: 'advanced',
      investment_timeline: 'short',
      investment_priorities: ['stability', 'income', 'liquidity'],
      savings_rate: 30,
      spending_tracking: 'monthly',
      budget_adherence: 'always',
      financial_stress_level: 2,
    }
  },
  {
    id: 'retiree',
    name: 'Retiree',
    description: 'Fixed income, focus on preservation and withdrawals',
    icon: '🌅',
    ageRange: '65+',
    answers: {
      current_age: 68,
      dependents: 0,
      marital_status: 'widowed',
      gross_monthly_income: 7000, // from pensions, social security, withdrawals
      net_monthly_income: 7000,
      income_stability: 'very_stable',
      additional_income_sources: ['investment_dividends', 'government_benefits'],
      annual_bonus: 0,
      housing_cost: 600, // (taxes and insurance)
      housing_type: 'owned_outright',
      food_expenses: 600,
      transportation_expenses: 300,
      healthcare_expenses: 1500,
      insurance_expenses: 500,
      entertainment_expenses: 800,
      other_monthly_expenses: 400,
      emergency_fund: 50000,
      checking_account: 10000,
      savings_account: 80000,
      investment_accounts: 300000,
      retirement_accounts: 800000,
      real_estate_value: 500000,
      other_assets: 20000,
      credit_card_debt: 0,
      credit_card_interest_rate: 0,
      student_loan_debt: 0,
      student_loan_interest_rate: 0,
      mortgage_balance: 0,
      mortgage_interest_rate: 0,
      auto_loan_balance: 0,
      auto_loan_interest_rate: 0,
      other_debt: 0,
      other_debt_interest_rate: 0,
      retirement_age: 65,
      desired_retirement_income: 7000,
      short_term_goals: [],
      medium_term_goals: [],
      long_term_goals: ['legacy_wealth', 'charity_giving'],
      major_purchase_timeline: 'None',
      risk_tolerance: 'conservative',
      investment_experience: 'expert',
      investment_timeline: 'short',
      investment_priorities: ['stability', 'income', 'liquidity'],
      savings_rate: 5, // low savings rate, focus is on spending
      spending_tracking: 'monthly',
      budget_adherence: 'always',
      financial_stress_level: 3,
    }
  }
];