/**
 * Currency code to symbol mapping
 * Maps ISO 4217 currency codes to their common symbols
 */
export const CURRENCY_SYMBOLS: Record<string, string> = {
  'AED': 'د.إ',
  'ARS': 'ARS$',
  'AUD': 'A$',
  'BRL': 'R$',
  'CAD': 'C$',
  'CHF': 'CHF',
  'CLP': 'CLP$',
  'CNY': '¥',
  'CZK': 'Kč',
  'DKK': 'kr',
  'DOP': 'RD$',
  'EGP': 'E£',
  'EUR': '€',
  'GBP': '£',
  'GHS': '₵',
  'GTQ': 'Q',
  'HKD': 'HK$',
  'JMD': 'J$',
  'IDR': 'Rp',
  'INR': '₹',
  'JPY': '¥',
  'KES': 'KSh',
  'KRW': '₩',
  'LKR': 'Rs',
  'MXN': 'MX$',
  'MYR': 'RM',
  'MWK': 'MK',
  'NGN': '₦',
  'NOK': 'kr',
  'NZD': 'NZ$',
  'PHP': '₱',
  'PEN': 'S/',
  'PLN': 'zł',
  'PKR': '₨',
  'PYG': '₲',
  'RSD': 'Дин.',
  'RON': 'RON',
  'RUB': '₽',
  'SAR': 'ر.س',
  'SEK': 'kr',
  'SGD': 'S$',
  'THB': '฿',
  'TWD': 'NT$',
  'TRY': '₺',
  'UAH': '₴',
  'USD': '$',
  'VND': '₫',
  'ZAR': 'R',
  'HUF': 'Ft',
  'MMK': 'Ks',
  'JOD': 'د.أ',
  'SYP': '£S',
  'ZMW': 'ZK',
};

export function getCurrencySymbolBasedOnTimeZone(): string {
  // Mapping of timezone identifiers to currency codes
  const timezoneToCurrency: Record<string, string> = {
    // North America
    'America/New_York': 'USD',
    'America/Los_Angeles': 'USD',
    'America/Chicago': 'USD',
    'America/Denver': 'USD',
    'America/Phoenix': 'USD',
    'America/Anchorage': 'USD',
    'America/Toronto': 'CAD',
    'America/Vancouver': 'CAD',
    'America/Montreal': 'CAD',
    'America/Edmonton': 'CAD',
    'America/Winnipeg': 'CAD',
    'America/Halifax': 'CAD',
    'America/Mexico_City': 'MXN',
    'America/Monterrey': 'MXN',
    'America/Guadalajara': 'MXN',
    'America/Argentina/Buenos_Aires': 'ARS',
    'America/Santo_Domingo': 'DOP',
    'America/Jamaica': 'JMD',
    'America/Port-au-Prince': 'HTG',
    
    // Europe
    'Europe/London': 'GBP',
    'Europe/Paris': 'EUR',
    'Europe/Berlin': 'EUR',
    'Europe/Rome': 'EUR',
    'Europe/Madrid': 'EUR',
    'Europe/Amsterdam': 'EUR',
    'Europe/Brussels': 'EUR',
    'Europe/Vienna': 'EUR',
    'Europe/Zurich': 'CHF',
    'Europe/Stockholm': 'SEK',
    'Europe/Oslo': 'NOK',
    'Europe/Copenhagen': 'DKK',
    'Europe/Helsinki': 'EUR',
    'Europe/Dublin': 'EUR',
    'Europe/Warsaw': 'PLN',
    'Europe/Prague': 'CZK',
    'Europe/Budapest': 'HUF',
    'Europe/Belgrade': 'RSD',
    'Europe/Athens': 'EUR',
    'Europe/Lisbon': 'EUR',
    'Europe/Moscow': 'RUB',
    'Europe/Kiev': 'UAH',
    'Europe/Sofia': 'BGN',
    'Europe/Bucharest': 'RON',
    'Europe/Zagreb': 'HRK',
    
    // Asia
    'Asia/Tokyo': 'JPY',
    'Asia/Shanghai': 'CNY',
    'Asia/Beijing': 'CNY',
    'Asia/Hong_Kong': 'HKD',
    'Asia/Seoul': 'KRW',
    'Asia/Singapore': 'SGD',
    'Asia/Bangkok': 'THB',
    'Asia/Jakarta': 'IDR',
    'Asia/Manila': 'PHP',
    'Asia/Kuala_Lumpur': 'MYR',
    'Asia/Mumbai': 'INR',
    'Asia/Kolkata': 'INR',
    'Asia/Dubai': 'AED',
    'Asia/Riyadh': 'SAR',
    'Asia/Taipei': 'TWD',
    'Asia/Karachi': 'PKR',
    'Asia/Dhaka': 'BDT',
    'Asia/Colombo': 'LKR',
    'Asia/Kathmandu': 'NPR',
    'Asia/Thimphu': 'BTN',
    'Asia/Yangon': 'MMK',
    'Asia/Amman': 'JOD',
    'Asia/Damascus': 'SYP',
    'Asia/Ho_Chi_Minh': 'VND',
    'Asia/Phnom_Penh': 'KHR',
    'Asia/Vientiane': 'LAK',
    'Asia/Bishkek': 'KGS',
    'Asia/Dushanbe': 'TJS',
    'Asia/Ashgabat': 'TMT',
    'Asia/Tashkent': 'UZS',
    'Asia/Almaty': 'KZT',
    'Asia/Baku': 'AZN',
    'Asia/Yerevan': 'AMD',
    'Asia/Tbilisi': 'GEL',
    
    // Middle East
    'Asia/Jerusalem': 'ILS',
    'Asia/Baghdad': 'IQD',
    'Asia/Kuwait': 'KWD',
    'Asia/Bahrain': 'BHD',
    'Asia/Qatar': 'QAR',
    'Asia/Muscat': 'OMR',
    'Asia/Aden': 'YER',
    'Asia/Tehran': 'IRR',
    
    // Oceania
    'Australia/Sydney': 'AUD',
    'Australia/Melbourne': 'AUD',
    'Australia/Brisbane': 'AUD',
    'Australia/Perth': 'AUD',
    'Australia/Adelaide': 'AUD',
    'Australia/Darwin': 'AUD',
    'Australia/Hobart': 'AUD',
    'Australia/Canberra': 'AUD',
    'Pacific/Auckland': 'NZD',
    'Pacific/Fiji': 'FJD',
    'Pacific/Guam': 'USD',
    'Pacific/Samoa': 'WST',
    'Pacific/Tongatapu': 'TOP',
    'Pacific/Noumea': 'XPF',
    'Pacific/Tahiti': 'XPF',
    'Pacific/Port_Moresby': 'PGK',
    'Pacific/Honolulu': 'USD',
    'Pacific/Majuro': 'USD',
    'Pacific/Tarawa': 'AUD',
    'Pacific/Funafuti': 'AUD',
    'Pacific/Kiritimati': 'AUD',
    
    // South America
    'America/Sao_Paulo': 'BRL',
    'America/Buenos_Aires': 'ARS',
    'America/Santiago': 'CLP',
    'America/Lima': 'PEN',
    'America/Bogota': 'COP',
    'America/Caracas': 'VES',
    'America/Guayaquil': 'USD',
    'America/La_Paz': 'BOB',
    'America/Asuncion': 'PYG',
    'America/Montevideo': 'UYU',
    'America/Paramaribo': 'SRD',
    'America/Cayenne': 'EUR',
    'America/Porto_Velho': 'BRL',
    'America/Recife': 'BRL',
    'America/Fortaleza': 'BRL',
    'America/Belem': 'BRL',
    'America/Cuiaba': 'BRL',
    'America/Campo_Grande': 'BRL',
    'America/Salvador': 'BRL',
    'America/Araguaina': 'BRL',
    'America/Maceio': 'BRL',
    'America/Bahia': 'BRL',
    'America/Rio_Branco': 'BRL',
    'America/Eirunepe': 'BRL',
    'America/Boa_Vista': 'BRL',
    'America/Manaus': 'BRL',
    
    // Africa
    'Africa/Johannesburg': 'ZAR',
    'Africa/Cairo': 'EGP',
    'Africa/Lagos': 'NGN',
    'Africa/Nairobi': 'KES',
    'Africa/Casablanca': 'MAD',
    'Africa/Algiers': 'DZD',
    'Africa/Tunis': 'TND',
    'Africa/Tripoli': 'LYD',
    'Africa/Addis_Ababa': 'ETB',
    'Africa/Khartoum': 'SDG',
    'Africa/Djibouti': 'DJF',
    'Africa/Mogadishu': 'SOS',
    'Africa/Dar_es_Salaam': 'TZS',
    'Africa/Kampala': 'UGX',
    'Africa/Kigali': 'RWF',
    'Africa/Bujumbura': 'BIF',
    'Africa/Lubumbashi': 'CDF',
    'Africa/Kinshasa': 'CDF',
    'Africa/Luanda': 'AOA',
    'Africa/Windhoek': 'NAD',
    'Africa/Gaborone': 'BWP',
    'Africa/Maseru': 'LSL',
    'Africa/Mbabane': 'SZL',
    'Africa/Maputo': 'MZN',
    'Africa/Blantyre': 'MWK',
    'Africa/Lusaka': 'ZMW',
    'Africa/Harare': 'ZWL',
    'Africa/Douala': 'XAF',
    'Africa/Bangui': 'XAF',
    'Africa/Brazzaville': 'XAF',
    'Africa/Libreville': 'XAF',
    'Africa/Malabo': 'XAF',
    'Africa/Niamey': 'XOF',
    'Africa/Ouagadougou': 'XOF',
    'Africa/Abidjan': 'XOF',
    'Africa/Lome': 'XOF',
    'Africa/Porto-Novo': 'XOF',
    'Africa/Dakar': 'XOF',
    'Africa/Bamako': 'XOF',
    'Africa/Conakry': 'GNF',
    'Africa/Freetown': 'SLL',
    'Africa/Monrovia': 'LRD',
    'Africa/Nouakchott': 'MRU',
    'Africa/Banjul': 'GMD',
    'Africa/Bissau': 'XOF',
    'Africa/Praia': 'CVE',
    'Africa/Sao_Tome': 'STN',
    'Africa/Asmara': 'ERN',
    'Africa/Stanley': 'FKP',
    'Africa/Juba': 'SSP',
    'Africa/Comoro': 'KMF',
    'Africa/Mayotte': 'EUR',
    'Africa/Reunion': 'EUR',
    'Africa/Mauritius': 'MUR',
    'Africa/Seychelles': 'SCR',
    
    // Central America & Caribbean
    'America/Guatemala': 'GTQ',
    'America/Tegucigalpa': 'HNL',
    'America/Managua': 'NIO',
    'America/San_Jose': 'CRC',
    'America/Panama': 'PAB',
    'America/Belize': 'BZD',
    'America/El_Salvador': 'USD',
    'America/Costa_Rica': 'CRC',
    'America/Puerto_Rico': 'USD',
    'America/Virgin': 'USD',
    'America/Barbados': 'BBD',
    'America/Trinidad': 'TTD',
    'America/Grenada': 'XCD',
    'America/St_Vincent': 'XCD',
    'America/St_Lucia': 'XCD',
    'America/Dominica': 'XCD',
    'America/Antigua': 'XCD',
    'America/St_Kitts': 'XCD',
    'America/Montserrat': 'XCD',
    'America/Anguilla': 'XCD',
    'America/Tortola': 'USD',
    'America/Grand_Turk': 'USD',
    'America/Cayman': 'KYD',
    'America/Nassau': 'BSD',
    'America/Bermuda': 'BMD',
    'America/Danmarkshavn': 'DKK',
    'America/Godthab': 'DKK',
    'America/Thule': 'USD',
    'America/Scoresbysund': 'DKK',
    
    // Indian Ocean
    'Indian/Maldives': 'MVR',
    'Indian/Chagos': 'USD',
    'Indian/Christmas': 'AUD',
    'Indian/Cocos': 'AUD',
    'Indian/Kerguelen': 'EUR',
    'Indian/Mahe': 'SCR',
    'Indian/Mauritius': 'MUR',
    'Indian/Reunion': 'EUR',
    'Indian/Antananarivo': 'MGA',
    'Indian/Comoro': 'KMF',
    'Indian/Mayotte': 'EUR',
    
    // Antarctica
    'Antarctica/Casey': 'AUD',
    'Antarctica/Davis': 'AUD',
    'Antarctica/Mawson': 'AUD',
    'Antarctica/DumontDUrville': 'XPF',
    'Antarctica/Syowa': 'JPY',
    'Antarctica/Vostok': 'RUB',
    'Antarctica/Palmer': 'CLP',
    'Antarctica/Rothera': 'GBP',
    'Antarctica/Troll': 'NOK',
    'Antarctica/McMurdo': 'NZD',
    
    // Atlantic
    'Atlantic/Azores': 'EUR',
    'Atlantic/Bermuda': 'BMD',
    'Atlantic/Canary': 'EUR',
    'Atlantic/Faroe': 'DKK',
    'Atlantic/Madeira': 'EUR',
    'Atlantic/Reykjavik': 'ISK',
    'Atlantic/South_Georgia': 'GBP',
    'Atlantic/St_Helena': 'SHP',
    'Atlantic/Stanley': 'FKP',
    'Atlantic/Cape_Verde': 'CVE',
    
    // Additional timezone coverage for better accuracy
    'US/Eastern': 'USD',
    'US/Central': 'USD',
    'US/Mountain': 'USD',
    'US/Pacific': 'USD',
    'US/Alaska': 'USD',
    'US/Hawaii': 'USD',
    'US/Samoa': 'USD',
    'Canada/Eastern': 'CAD',
    'Canada/Central': 'CAD',
    'Canada/Mountain': 'CAD',
    'Canada/Pacific': 'CAD',
    'Mexico/General': 'MXN',
    'Brazil/East': 'BRL',
    'Brazil/West': 'BRL',
    'Argentina/Buenos_Aires': 'ARS',
    'Chile/Continental': 'CLP',
    'Colombia/Bogota': 'COP',
    'Peru/Lima': 'PEN',
    'Venezuela/Caracas': 'VES',
  };

  try {
    // Get the user's timezone
    const timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
    
    // Look up the currency for this timezone
    const currencyCode = timezoneToCurrency[timeZone];
    
    if (currencyCode && CURRENCY_SYMBOLS[currencyCode]) {
      return CURRENCY_SYMBOLS[currencyCode];
    }
    
    // Fallback to USD if timezone not found
    return CURRENCY_SYMBOLS['USD'];
  } catch (error) {
    // If anything fails, fallback to dollar sign
    return CURRENCY_SYMBOLS['USD'];
  }
}