/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TermsOfServiceImport } from './routes/terms-of-service'
import { Route as ResultsImport } from './routes/results'
import { Route as PrivacyPolicyImport } from './routes/privacy-policy'
import { Route as IntroImport } from './routes/intro'
import { Route as CookiePolicyImport } from './routes/cookie-policy'
import { Route as ChatImport } from './routes/chat'
import { Route as RegisterRouteImport } from './routes/register/route'
import { Route as ProfileRouteImport } from './routes/profile/route'
import { Route as OnboardingRouteImport } from './routes/onboarding/route'
import { Route as LoginRouteImport } from './routes/login/route'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as IndexImport } from './routes/index'
import { Route as RegisterIndexImport } from './routes/register/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as OnboardingIndexImport } from './routes/onboarding/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as LearningIndexImport } from './routes/learning/index'
import { Route as FormatIndexImport } from './routes/format/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as CalculatorsIndexImport } from './routes/calculators/index'
import { Route as AuthorIndexImport } from './routes/author/index'
import { Route as CalculatorsSavingGoalsCalculatorImport } from './routes/calculators/saving-goals-calculator'
import { Route as CalculatorsRetirementCalculatorImport } from './routes/calculators/retirement-calculator'
import { Route as CalculatorsMortgageCalculatorImport } from './routes/calculators/mortgage-calculator'
import { Route as CalculatorsInvestmentCalculatorImport } from './routes/calculators/investment-calculator'
import { Route as CalculatorsCompoundCalculatorImport } from './routes/calculators/compound-calculator'
import { Route as CalculatorsAutoLoanCalculatorImport } from './routes/calculators/auto-loan-calculator'
import { Route as AuthorImportImport } from './routes/author/import'
import { Route as LearningCourseIdIndexImport } from './routes/learning/$courseId/index'
import { Route as AuthorCourseCourseIdImport } from './routes/author/course/$courseId'
import { Route as LearningCourseIdLessonLessonIdImport } from './routes/learning/$courseId/lesson/$lessonId'

// Create/Update Routes

const TermsOfServiceRoute = TermsOfServiceImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRoute,
} as any)

const ResultsRoute = ResultsImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyPolicyRoute = PrivacyPolicyImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRoute,
} as any)

const IntroRoute = IntroImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRoute,
} as any)

const CookiePolicyRoute = CookiePolicyImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRoute,
} as any)

const ChatRoute = ChatImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRouteRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRouteRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingRouteRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const LoginRouteRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterIndexRoute = RegisterIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRouteRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRouteRoute,
} as any)

const OnboardingIndexRoute = OnboardingIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)

const LearningIndexRoute = LearningIndexImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => rootRoute,
} as any)

const FormatIndexRoute = FormatIndexImport.update({
  id: '/format/',
  path: '/format/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const CalculatorsIndexRoute = CalculatorsIndexImport.update({
  id: '/calculators/',
  path: '/calculators/',
  getParentRoute: () => rootRoute,
} as any)

const AuthorIndexRoute = AuthorIndexImport.update({
  id: '/author/',
  path: '/author/',
  getParentRoute: () => rootRoute,
} as any)

const CalculatorsSavingGoalsCalculatorRoute =
  CalculatorsSavingGoalsCalculatorImport.update({
    id: '/calculators/saving-goals-calculator',
    path: '/calculators/saving-goals-calculator',
    getParentRoute: () => rootRoute,
  } as any)

const CalculatorsRetirementCalculatorRoute =
  CalculatorsRetirementCalculatorImport.update({
    id: '/calculators/retirement-calculator',
    path: '/calculators/retirement-calculator',
    getParentRoute: () => rootRoute,
  } as any)

const CalculatorsMortgageCalculatorRoute =
  CalculatorsMortgageCalculatorImport.update({
    id: '/calculators/mortgage-calculator',
    path: '/calculators/mortgage-calculator',
    getParentRoute: () => rootRoute,
  } as any)

const CalculatorsInvestmentCalculatorRoute =
  CalculatorsInvestmentCalculatorImport.update({
    id: '/calculators/investment-calculator',
    path: '/calculators/investment-calculator',
    getParentRoute: () => rootRoute,
  } as any)

const CalculatorsCompoundCalculatorRoute =
  CalculatorsCompoundCalculatorImport.update({
    id: '/calculators/compound-calculator',
    path: '/calculators/compound-calculator',
    getParentRoute: () => rootRoute,
  } as any)

const CalculatorsAutoLoanCalculatorRoute =
  CalculatorsAutoLoanCalculatorImport.update({
    id: '/calculators/auto-loan-calculator',
    path: '/calculators/auto-loan-calculator',
    getParentRoute: () => rootRoute,
  } as any)

const AuthorImportRoute = AuthorImportImport.update({
  id: '/author/import',
  path: '/author/import',
  getParentRoute: () => rootRoute,
} as any)

const LearningCourseIdIndexRoute = LearningCourseIdIndexImport.update({
  id: '/learning/$courseId/',
  path: '/learning/$courseId/',
  getParentRoute: () => rootRoute,
} as any)

const AuthorCourseCourseIdRoute = AuthorCourseCourseIdImport.update({
  id: '/author/course/$courseId',
  path: '/author/course/$courseId',
  getParentRoute: () => rootRoute,
} as any)

const LearningCourseIdLessonLessonIdRoute =
  LearningCourseIdLessonLessonIdImport.update({
    id: '/learning/$courseId/lesson/$lessonId',
    path: '/learning/$courseId/lesson/$lessonId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRoute
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatImport
      parentRoute: typeof rootRoute
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyImport
      parentRoute: typeof rootRoute
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroImport
      parentRoute: typeof rootRoute
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyImport
      parentRoute: typeof rootRoute
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsImport
      parentRoute: typeof rootRoute
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceImport
      parentRoute: typeof rootRoute
    }
    '/author/import': {
      id: '/author/import'
      path: '/author/import'
      fullPath: '/author/import'
      preLoaderRoute: typeof AuthorImportImport
      parentRoute: typeof rootRoute
    }
    '/calculators/auto-loan-calculator': {
      id: '/calculators/auto-loan-calculator'
      path: '/calculators/auto-loan-calculator'
      fullPath: '/calculators/auto-loan-calculator'
      preLoaderRoute: typeof CalculatorsAutoLoanCalculatorImport
      parentRoute: typeof rootRoute
    }
    '/calculators/compound-calculator': {
      id: '/calculators/compound-calculator'
      path: '/calculators/compound-calculator'
      fullPath: '/calculators/compound-calculator'
      preLoaderRoute: typeof CalculatorsCompoundCalculatorImport
      parentRoute: typeof rootRoute
    }
    '/calculators/investment-calculator': {
      id: '/calculators/investment-calculator'
      path: '/calculators/investment-calculator'
      fullPath: '/calculators/investment-calculator'
      preLoaderRoute: typeof CalculatorsInvestmentCalculatorImport
      parentRoute: typeof rootRoute
    }
    '/calculators/mortgage-calculator': {
      id: '/calculators/mortgage-calculator'
      path: '/calculators/mortgage-calculator'
      fullPath: '/calculators/mortgage-calculator'
      preLoaderRoute: typeof CalculatorsMortgageCalculatorImport
      parentRoute: typeof rootRoute
    }
    '/calculators/retirement-calculator': {
      id: '/calculators/retirement-calculator'
      path: '/calculators/retirement-calculator'
      fullPath: '/calculators/retirement-calculator'
      preLoaderRoute: typeof CalculatorsRetirementCalculatorImport
      parentRoute: typeof rootRoute
    }
    '/calculators/saving-goals-calculator': {
      id: '/calculators/saving-goals-calculator'
      path: '/calculators/saving-goals-calculator'
      fullPath: '/calculators/saving-goals-calculator'
      preLoaderRoute: typeof CalculatorsSavingGoalsCalculatorImport
      parentRoute: typeof rootRoute
    }
    '/author/': {
      id: '/author/'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorIndexImport
      parentRoute: typeof rootRoute
    }
    '/calculators/': {
      id: '/calculators/'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/format/': {
      id: '/format/'
      path: '/format'
      fullPath: '/format'
      preLoaderRoute: typeof FormatIndexImport
      parentRoute: typeof rootRoute
    }
    '/learning/': {
      id: '/learning/'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof LoginRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof ProfileRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexImport
      parentRoute: typeof RegisterRouteImport
    }
    '/author/course/$courseId': {
      id: '/author/course/$courseId'
      path: '/author/course/$courseId'
      fullPath: '/author/course/$courseId'
      preLoaderRoute: typeof AuthorCourseCourseIdImport
      parentRoute: typeof rootRoute
    }
    '/learning/$courseId/': {
      id: '/learning/$courseId/'
      path: '/learning/$courseId'
      fullPath: '/learning/$courseId'
      preLoaderRoute: typeof LearningCourseIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/learning/$courseId/lesson/$lessonId': {
      id: '/learning/$courseId/lesson/$lessonId'
      path: '/learning/$courseId/lesson/$lessonId'
      fullPath: '/learning/$courseId/lesson/$lessonId'
      preLoaderRoute: typeof LearningCourseIdLessonLessonIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface ProfileRouteRouteChildren {
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

interface RegisterRouteRouteChildren {
  RegisterIndexRoute: typeof RegisterIndexRoute
}

const RegisterRouteRouteChildren: RegisterRouteRouteChildren = {
  RegisterIndexRoute: RegisterIndexRoute,
}

const RegisterRouteRouteWithChildren = RegisterRouteRoute._addFileChildren(
  RegisterRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/register': typeof RegisterRouteRouteWithChildren
  '/chat': typeof ChatRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/intro': typeof IntroRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/results': typeof ResultsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/author/import': typeof AuthorImportRoute
  '/calculators/auto-loan-calculator': typeof CalculatorsAutoLoanCalculatorRoute
  '/calculators/compound-calculator': typeof CalculatorsCompoundCalculatorRoute
  '/calculators/investment-calculator': typeof CalculatorsInvestmentCalculatorRoute
  '/calculators/mortgage-calculator': typeof CalculatorsMortgageCalculatorRoute
  '/calculators/retirement-calculator': typeof CalculatorsRetirementCalculatorRoute
  '/calculators/saving-goals-calculator': typeof CalculatorsSavingGoalsCalculatorRoute
  '/author': typeof AuthorIndexRoute
  '/calculators': typeof CalculatorsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/format': typeof FormatIndexRoute
  '/learning': typeof LearningIndexRoute
  '/login/': typeof LoginIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/author/course/$courseId': typeof AuthorCourseCourseIdRoute
  '/learning/$courseId': typeof LearningCourseIdIndexRoute
  '/learning/$courseId/lesson/$lessonId': typeof LearningCourseIdLessonLessonIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/intro': typeof IntroRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/results': typeof ResultsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/author/import': typeof AuthorImportRoute
  '/calculators/auto-loan-calculator': typeof CalculatorsAutoLoanCalculatorRoute
  '/calculators/compound-calculator': typeof CalculatorsCompoundCalculatorRoute
  '/calculators/investment-calculator': typeof CalculatorsInvestmentCalculatorRoute
  '/calculators/mortgage-calculator': typeof CalculatorsMortgageCalculatorRoute
  '/calculators/retirement-calculator': typeof CalculatorsRetirementCalculatorRoute
  '/calculators/saving-goals-calculator': typeof CalculatorsSavingGoalsCalculatorRoute
  '/author': typeof AuthorIndexRoute
  '/calculators': typeof CalculatorsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/format': typeof FormatIndexRoute
  '/learning': typeof LearningIndexRoute
  '/login': typeof LoginIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/register': typeof RegisterIndexRoute
  '/author/course/$courseId': typeof AuthorCourseCourseIdRoute
  '/learning/$courseId': typeof LearningCourseIdIndexRoute
  '/learning/$courseId/lesson/$lessonId': typeof LearningCourseIdLessonLessonIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/register': typeof RegisterRouteRouteWithChildren
  '/chat': typeof ChatRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/intro': typeof IntroRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/results': typeof ResultsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/author/import': typeof AuthorImportRoute
  '/calculators/auto-loan-calculator': typeof CalculatorsAutoLoanCalculatorRoute
  '/calculators/compound-calculator': typeof CalculatorsCompoundCalculatorRoute
  '/calculators/investment-calculator': typeof CalculatorsInvestmentCalculatorRoute
  '/calculators/mortgage-calculator': typeof CalculatorsMortgageCalculatorRoute
  '/calculators/retirement-calculator': typeof CalculatorsRetirementCalculatorRoute
  '/calculators/saving-goals-calculator': typeof CalculatorsSavingGoalsCalculatorRoute
  '/author/': typeof AuthorIndexRoute
  '/calculators/': typeof CalculatorsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/format/': typeof FormatIndexRoute
  '/learning/': typeof LearningIndexRoute
  '/login/': typeof LoginIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/author/course/$courseId': typeof AuthorCourseCourseIdRoute
  '/learning/$courseId/': typeof LearningCourseIdIndexRoute
  '/learning/$courseId/lesson/$lessonId': typeof LearningCourseIdLessonLessonIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/chat'
    | '/cookie-policy'
    | '/intro'
    | '/privacy-policy'
    | '/results'
    | '/terms-of-service'
    | '/author/import'
    | '/calculators/auto-loan-calculator'
    | '/calculators/compound-calculator'
    | '/calculators/investment-calculator'
    | '/calculators/mortgage-calculator'
    | '/calculators/retirement-calculator'
    | '/calculators/saving-goals-calculator'
    | '/author'
    | '/calculators'
    | '/dashboard/'
    | '/format'
    | '/learning'
    | '/login/'
    | '/onboarding/'
    | '/profile/'
    | '/register/'
    | '/author/course/$courseId'
    | '/learning/$courseId'
    | '/learning/$courseId/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/cookie-policy'
    | '/intro'
    | '/privacy-policy'
    | '/results'
    | '/terms-of-service'
    | '/author/import'
    | '/calculators/auto-loan-calculator'
    | '/calculators/compound-calculator'
    | '/calculators/investment-calculator'
    | '/calculators/mortgage-calculator'
    | '/calculators/retirement-calculator'
    | '/calculators/saving-goals-calculator'
    | '/author'
    | '/calculators'
    | '/dashboard'
    | '/format'
    | '/learning'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/author/course/$courseId'
    | '/learning/$courseId'
    | '/learning/$courseId/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/chat'
    | '/cookie-policy'
    | '/intro'
    | '/privacy-policy'
    | '/results'
    | '/terms-of-service'
    | '/author/import'
    | '/calculators/auto-loan-calculator'
    | '/calculators/compound-calculator'
    | '/calculators/investment-calculator'
    | '/calculators/mortgage-calculator'
    | '/calculators/retirement-calculator'
    | '/calculators/saving-goals-calculator'
    | '/author/'
    | '/calculators/'
    | '/dashboard/'
    | '/format/'
    | '/learning/'
    | '/login/'
    | '/onboarding/'
    | '/profile/'
    | '/register/'
    | '/author/course/$courseId'
    | '/learning/$courseId/'
    | '/learning/$courseId/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  RegisterRouteRoute: typeof RegisterRouteRouteWithChildren
  ChatRoute: typeof ChatRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  IntroRoute: typeof IntroRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResultsRoute: typeof ResultsRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  AuthorImportRoute: typeof AuthorImportRoute
  CalculatorsAutoLoanCalculatorRoute: typeof CalculatorsAutoLoanCalculatorRoute
  CalculatorsCompoundCalculatorRoute: typeof CalculatorsCompoundCalculatorRoute
  CalculatorsInvestmentCalculatorRoute: typeof CalculatorsInvestmentCalculatorRoute
  CalculatorsMortgageCalculatorRoute: typeof CalculatorsMortgageCalculatorRoute
  CalculatorsRetirementCalculatorRoute: typeof CalculatorsRetirementCalculatorRoute
  CalculatorsSavingGoalsCalculatorRoute: typeof CalculatorsSavingGoalsCalculatorRoute
  AuthorIndexRoute: typeof AuthorIndexRoute
  CalculatorsIndexRoute: typeof CalculatorsIndexRoute
  FormatIndexRoute: typeof FormatIndexRoute
  LearningIndexRoute: typeof LearningIndexRoute
  AuthorCourseCourseIdRoute: typeof AuthorCourseCourseIdRoute
  LearningCourseIdIndexRoute: typeof LearningCourseIdIndexRoute
  LearningCourseIdLessonLessonIdRoute: typeof LearningCourseIdLessonLessonIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  RegisterRouteRoute: RegisterRouteRouteWithChildren,
  ChatRoute: ChatRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  IntroRoute: IntroRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResultsRoute: ResultsRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  AuthorImportRoute: AuthorImportRoute,
  CalculatorsAutoLoanCalculatorRoute: CalculatorsAutoLoanCalculatorRoute,
  CalculatorsCompoundCalculatorRoute: CalculatorsCompoundCalculatorRoute,
  CalculatorsInvestmentCalculatorRoute: CalculatorsInvestmentCalculatorRoute,
  CalculatorsMortgageCalculatorRoute: CalculatorsMortgageCalculatorRoute,
  CalculatorsRetirementCalculatorRoute: CalculatorsRetirementCalculatorRoute,
  CalculatorsSavingGoalsCalculatorRoute: CalculatorsSavingGoalsCalculatorRoute,
  AuthorIndexRoute: AuthorIndexRoute,
  CalculatorsIndexRoute: CalculatorsIndexRoute,
  FormatIndexRoute: FormatIndexRoute,
  LearningIndexRoute: LearningIndexRoute,
  AuthorCourseCourseIdRoute: AuthorCourseCourseIdRoute,
  LearningCourseIdIndexRoute: LearningCourseIdIndexRoute,
  LearningCourseIdLessonLessonIdRoute: LearningCourseIdLessonLessonIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/login",
        "/onboarding",
        "/profile",
        "/register",
        "/chat",
        "/cookie-policy",
        "/intro",
        "/privacy-policy",
        "/results",
        "/terms-of-service",
        "/author/import",
        "/calculators/auto-loan-calculator",
        "/calculators/compound-calculator",
        "/calculators/investment-calculator",
        "/calculators/mortgage-calculator",
        "/calculators/retirement-calculator",
        "/calculators/saving-goals-calculator",
        "/author/",
        "/calculators/",
        "/format/",
        "/learning/",
        "/author/course/$courseId",
        "/learning/$courseId/",
        "/learning/$courseId/lesson/$lessonId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/"
      ]
    },
    "/login": {
      "filePath": "login/route.tsx",
      "children": [
        "/login/"
      ]
    },
    "/onboarding": {
      "filePath": "onboarding/route.tsx",
      "children": [
        "/onboarding/"
      ]
    },
    "/profile": {
      "filePath": "profile/route.tsx",
      "children": [
        "/profile/"
      ]
    },
    "/register": {
      "filePath": "register/route.tsx",
      "children": [
        "/register/"
      ]
    },
    "/chat": {
      "filePath": "chat.tsx"
    },
    "/cookie-policy": {
      "filePath": "cookie-policy.tsx"
    },
    "/intro": {
      "filePath": "intro.tsx"
    },
    "/privacy-policy": {
      "filePath": "privacy-policy.tsx"
    },
    "/results": {
      "filePath": "results.tsx"
    },
    "/terms-of-service": {
      "filePath": "terms-of-service.tsx"
    },
    "/author/import": {
      "filePath": "author/import.tsx"
    },
    "/calculators/auto-loan-calculator": {
      "filePath": "calculators/auto-loan-calculator.tsx"
    },
    "/calculators/compound-calculator": {
      "filePath": "calculators/compound-calculator.tsx"
    },
    "/calculators/investment-calculator": {
      "filePath": "calculators/investment-calculator.tsx"
    },
    "/calculators/mortgage-calculator": {
      "filePath": "calculators/mortgage-calculator.tsx"
    },
    "/calculators/retirement-calculator": {
      "filePath": "calculators/retirement-calculator.tsx"
    },
    "/calculators/saving-goals-calculator": {
      "filePath": "calculators/saving-goals-calculator.tsx"
    },
    "/author/": {
      "filePath": "author/index.tsx"
    },
    "/calculators/": {
      "filePath": "calculators/index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/format/": {
      "filePath": "format/index.tsx"
    },
    "/learning/": {
      "filePath": "learning/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx",
      "parent": "/login"
    },
    "/onboarding/": {
      "filePath": "onboarding/index.tsx",
      "parent": "/onboarding"
    },
    "/profile/": {
      "filePath": "profile/index.tsx",
      "parent": "/profile"
    },
    "/register/": {
      "filePath": "register/index.tsx",
      "parent": "/register"
    },
    "/author/course/$courseId": {
      "filePath": "author/course/$courseId.tsx"
    },
    "/learning/$courseId/": {
      "filePath": "learning/$courseId/index.tsx"
    },
    "/learning/$courseId/lesson/$lessonId": {
      "filePath": "learning/$courseId/lesson/$lessonId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
