/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as RegisterRouteRouteImport } from './routes/register/route'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as FormatIndexRouteImport } from './routes/format/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as AuthorIndexRouteImport } from './routes/author/index'
import { Route as BlogsBlogIdRouteImport } from './routes/blogs/$blogId'
import { Route as AuthorImportRouteImport } from './routes/author/import'
import { Route as DashboardUserSettingsIndexRouteImport } from './routes/dashboard/user-settings/index'
import { Route as DashboardLearningIndexRouteImport } from './routes/dashboard/learning/index'
import { Route as DashboardEssentialsIndexRouteImport } from './routes/dashboard/essentials/index'
import { Route as DashboardChatIndexRouteImport } from './routes/dashboard/chat/index'
import { Route as DashboardCalculatorsIndexRouteImport } from './routes/dashboard/calculators/index'
import { Route as DashboardLayoutIndexRouteImport } from './routes/dashboard/_layout.index'
import { Route as DashboardCalculatorsSavingGoalsCalculatorRouteImport } from './routes/dashboard/calculators/saving-goals-calculator'
import { Route as DashboardCalculatorsRetirementCalculatorRouteImport } from './routes/dashboard/calculators/retirement-calculator'
import { Route as DashboardCalculatorsMortgageCalculatorRouteImport } from './routes/dashboard/calculators/mortgage-calculator'
import { Route as DashboardCalculatorsInvestmentCalculatorRouteImport } from './routes/dashboard/calculators/investment-calculator'
import { Route as DashboardCalculatorsCompoundCalculatorRouteImport } from './routes/dashboard/calculators/compound-calculator'
import { Route as DashboardCalculatorsAutoLoanCalculatorRouteImport } from './routes/dashboard/calculators/auto-loan-calculator'
import { Route as DashboardLearningCourseIdIndexRouteImport } from './routes/dashboard/learning/$courseId/index'
import { Route as DashboardEssentialsCourseIdIndexRouteImport } from './routes/dashboard/essentials/$courseId/index'
import { Route as DashboardLearningCourseIdLessonLessonIdRouteImport } from './routes/dashboard/learning/$courseId/lesson/$lessonId'
import { Route as DashboardEssentialsCourseIdLessonLessonIdRouteImport } from './routes/dashboard/essentials/$courseId/lesson/$lessonId'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRouteRoute = RegisterRouteRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRouteRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const FormatIndexRoute = FormatIndexRouteImport.update({
  id: '/format/',
  path: '/format/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorIndexRoute = AuthorIndexRouteImport.update({
  id: '/author/',
  path: '/author/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlogIdRoute = BlogsBlogIdRouteImport.update({
  id: '/blogs/$blogId',
  path: '/blogs/$blogId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorImportRoute = AuthorImportRouteImport.update({
  id: '/author/import',
  path: '/author/import',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUserSettingsIndexRoute =
  DashboardUserSettingsIndexRouteImport.update({
    id: '/user-settings/',
    path: '/user-settings/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardLearningIndexRoute = DashboardLearningIndexRouteImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEssentialsIndexRoute =
  DashboardEssentialsIndexRouteImport.update({
    id: '/essentials/',
    path: '/essentials/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardChatIndexRoute = DashboardChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCalculatorsIndexRoute =
  DashboardCalculatorsIndexRouteImport.update({
    id: '/calculators/',
    path: '/calculators/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardLayoutIndexRoute = DashboardLayoutIndexRouteImport.update({
  id: '/_layout/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCalculatorsSavingGoalsCalculatorRoute =
  DashboardCalculatorsSavingGoalsCalculatorRouteImport.update({
    id: '/calculators/saving-goals-calculator',
    path: '/calculators/saving-goals-calculator',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCalculatorsRetirementCalculatorRoute =
  DashboardCalculatorsRetirementCalculatorRouteImport.update({
    id: '/calculators/retirement-calculator',
    path: '/calculators/retirement-calculator',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCalculatorsMortgageCalculatorRoute =
  DashboardCalculatorsMortgageCalculatorRouteImport.update({
    id: '/calculators/mortgage-calculator',
    path: '/calculators/mortgage-calculator',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCalculatorsInvestmentCalculatorRoute =
  DashboardCalculatorsInvestmentCalculatorRouteImport.update({
    id: '/calculators/investment-calculator',
    path: '/calculators/investment-calculator',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCalculatorsCompoundCalculatorRoute =
  DashboardCalculatorsCompoundCalculatorRouteImport.update({
    id: '/calculators/compound-calculator',
    path: '/calculators/compound-calculator',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCalculatorsAutoLoanCalculatorRoute =
  DashboardCalculatorsAutoLoanCalculatorRouteImport.update({
    id: '/calculators/auto-loan-calculator',
    path: '/calculators/auto-loan-calculator',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardLearningCourseIdIndexRoute =
  DashboardLearningCourseIdIndexRouteImport.update({
    id: '/learning/$courseId/',
    path: '/learning/$courseId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEssentialsCourseIdIndexRoute =
  DashboardEssentialsCourseIdIndexRouteImport.update({
    id: '/essentials/$courseId/',
    path: '/essentials/$courseId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardLearningCourseIdLessonLessonIdRoute =
  DashboardLearningCourseIdLessonLessonIdRouteImport.update({
    id: '/learning/$courseId/lesson/$lessonId',
    path: '/learning/$courseId/lesson/$lessonId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEssentialsCourseIdLessonLessonIdRoute =
  DashboardEssentialsCourseIdLessonLessonIdRouteImport.update({
    id: '/essentials/$courseId/lesson/$lessonId',
    path: '/essentials/$courseId/lesson/$lessonId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/register': typeof RegisterRouteRouteWithChildren
  '/cookie-policy': typeof CookiePolicyRoute
  '/intro': typeof IntroRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/author/import': typeof AuthorImportRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/author': typeof AuthorIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/format': typeof FormatIndexRoute
  '/login/': typeof LoginIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/dashboard/calculators/auto-loan-calculator': typeof DashboardCalculatorsAutoLoanCalculatorRoute
  '/dashboard/calculators/compound-calculator': typeof DashboardCalculatorsCompoundCalculatorRoute
  '/dashboard/calculators/investment-calculator': typeof DashboardCalculatorsInvestmentCalculatorRoute
  '/dashboard/calculators/mortgage-calculator': typeof DashboardCalculatorsMortgageCalculatorRoute
  '/dashboard/calculators/retirement-calculator': typeof DashboardCalculatorsRetirementCalculatorRoute
  '/dashboard/calculators/saving-goals-calculator': typeof DashboardCalculatorsSavingGoalsCalculatorRoute
  '/dashboard/': typeof DashboardLayoutIndexRoute
  '/dashboard/calculators': typeof DashboardCalculatorsIndexRoute
  '/dashboard/chat': typeof DashboardChatIndexRoute
  '/dashboard/essentials': typeof DashboardEssentialsIndexRoute
  '/dashboard/learning': typeof DashboardLearningIndexRoute
  '/dashboard/user-settings': typeof DashboardUserSettingsIndexRoute
  '/dashboard/essentials/$courseId': typeof DashboardEssentialsCourseIdIndexRoute
  '/dashboard/learning/$courseId': typeof DashboardLearningCourseIdIndexRoute
  '/dashboard/essentials/$courseId/lesson/$lessonId': typeof DashboardEssentialsCourseIdLessonLessonIdRoute
  '/dashboard/learning/$courseId/lesson/$lessonId': typeof DashboardLearningCourseIdLessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/intro': typeof IntroRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/author/import': typeof AuthorImportRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/author': typeof AuthorIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/format': typeof FormatIndexRoute
  '/login': typeof LoginIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/register': typeof RegisterIndexRoute
  '/dashboard/calculators/auto-loan-calculator': typeof DashboardCalculatorsAutoLoanCalculatorRoute
  '/dashboard/calculators/compound-calculator': typeof DashboardCalculatorsCompoundCalculatorRoute
  '/dashboard/calculators/investment-calculator': typeof DashboardCalculatorsInvestmentCalculatorRoute
  '/dashboard/calculators/mortgage-calculator': typeof DashboardCalculatorsMortgageCalculatorRoute
  '/dashboard/calculators/retirement-calculator': typeof DashboardCalculatorsRetirementCalculatorRoute
  '/dashboard/calculators/saving-goals-calculator': typeof DashboardCalculatorsSavingGoalsCalculatorRoute
  '/dashboard': typeof DashboardLayoutIndexRoute
  '/dashboard/calculators': typeof DashboardCalculatorsIndexRoute
  '/dashboard/chat': typeof DashboardChatIndexRoute
  '/dashboard/essentials': typeof DashboardEssentialsIndexRoute
  '/dashboard/learning': typeof DashboardLearningIndexRoute
  '/dashboard/user-settings': typeof DashboardUserSettingsIndexRoute
  '/dashboard/essentials/$courseId': typeof DashboardEssentialsCourseIdIndexRoute
  '/dashboard/learning/$courseId': typeof DashboardLearningCourseIdIndexRoute
  '/dashboard/essentials/$courseId/lesson/$lessonId': typeof DashboardEssentialsCourseIdLessonLessonIdRoute
  '/dashboard/learning/$courseId/lesson/$lessonId': typeof DashboardLearningCourseIdLessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/register': typeof RegisterRouteRouteWithChildren
  '/cookie-policy': typeof CookiePolicyRoute
  '/intro': typeof IntroRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/author/import': typeof AuthorImportRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/author/': typeof AuthorIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/format/': typeof FormatIndexRoute
  '/login/': typeof LoginIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/dashboard/calculators/auto-loan-calculator': typeof DashboardCalculatorsAutoLoanCalculatorRoute
  '/dashboard/calculators/compound-calculator': typeof DashboardCalculatorsCompoundCalculatorRoute
  '/dashboard/calculators/investment-calculator': typeof DashboardCalculatorsInvestmentCalculatorRoute
  '/dashboard/calculators/mortgage-calculator': typeof DashboardCalculatorsMortgageCalculatorRoute
  '/dashboard/calculators/retirement-calculator': typeof DashboardCalculatorsRetirementCalculatorRoute
  '/dashboard/calculators/saving-goals-calculator': typeof DashboardCalculatorsSavingGoalsCalculatorRoute
  '/dashboard/_layout/': typeof DashboardLayoutIndexRoute
  '/dashboard/calculators/': typeof DashboardCalculatorsIndexRoute
  '/dashboard/chat/': typeof DashboardChatIndexRoute
  '/dashboard/essentials/': typeof DashboardEssentialsIndexRoute
  '/dashboard/learning/': typeof DashboardLearningIndexRoute
  '/dashboard/user-settings/': typeof DashboardUserSettingsIndexRoute
  '/dashboard/essentials/$courseId/': typeof DashboardEssentialsCourseIdIndexRoute
  '/dashboard/learning/$courseId/': typeof DashboardLearningCourseIdIndexRoute
  '/dashboard/essentials/$courseId/lesson/$lessonId': typeof DashboardEssentialsCourseIdLessonLessonIdRoute
  '/dashboard/learning/$courseId/lesson/$lessonId': typeof DashboardLearningCourseIdLessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/cookie-policy'
    | '/intro'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/author/import'
    | '/blogs/$blogId'
    | '/author'
    | '/blogs'
    | '/format'
    | '/login/'
    | '/onboarding/'
    | '/register/'
    | '/dashboard/calculators/auto-loan-calculator'
    | '/dashboard/calculators/compound-calculator'
    | '/dashboard/calculators/investment-calculator'
    | '/dashboard/calculators/mortgage-calculator'
    | '/dashboard/calculators/retirement-calculator'
    | '/dashboard/calculators/saving-goals-calculator'
    | '/dashboard/'
    | '/dashboard/calculators'
    | '/dashboard/chat'
    | '/dashboard/essentials'
    | '/dashboard/learning'
    | '/dashboard/user-settings'
    | '/dashboard/essentials/$courseId'
    | '/dashboard/learning/$courseId'
    | '/dashboard/essentials/$courseId/lesson/$lessonId'
    | '/dashboard/learning/$courseId/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookie-policy'
    | '/intro'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/author/import'
    | '/blogs/$blogId'
    | '/author'
    | '/blogs'
    | '/format'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/dashboard/calculators/auto-loan-calculator'
    | '/dashboard/calculators/compound-calculator'
    | '/dashboard/calculators/investment-calculator'
    | '/dashboard/calculators/mortgage-calculator'
    | '/dashboard/calculators/retirement-calculator'
    | '/dashboard/calculators/saving-goals-calculator'
    | '/dashboard'
    | '/dashboard/calculators'
    | '/dashboard/chat'
    | '/dashboard/essentials'
    | '/dashboard/learning'
    | '/dashboard/user-settings'
    | '/dashboard/essentials/$courseId'
    | '/dashboard/learning/$courseId'
    | '/dashboard/essentials/$courseId/lesson/$lessonId'
    | '/dashboard/learning/$courseId/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/cookie-policy'
    | '/intro'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/author/import'
    | '/blogs/$blogId'
    | '/author/'
    | '/blogs/'
    | '/format/'
    | '/login/'
    | '/onboarding/'
    | '/register/'
    | '/dashboard/calculators/auto-loan-calculator'
    | '/dashboard/calculators/compound-calculator'
    | '/dashboard/calculators/investment-calculator'
    | '/dashboard/calculators/mortgage-calculator'
    | '/dashboard/calculators/retirement-calculator'
    | '/dashboard/calculators/saving-goals-calculator'
    | '/dashboard/_layout/'
    | '/dashboard/calculators/'
    | '/dashboard/chat/'
    | '/dashboard/essentials/'
    | '/dashboard/learning/'
    | '/dashboard/user-settings/'
    | '/dashboard/essentials/$courseId/'
    | '/dashboard/learning/$courseId/'
    | '/dashboard/essentials/$courseId/lesson/$lessonId'
    | '/dashboard/learning/$courseId/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  RegisterRouteRoute: typeof RegisterRouteRouteWithChildren
  CookiePolicyRoute: typeof CookiePolicyRoute
  IntroRoute: typeof IntroRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  AuthorImportRoute: typeof AuthorImportRoute
  BlogsBlogIdRoute: typeof BlogsBlogIdRoute
  AuthorIndexRoute: typeof AuthorIndexRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  FormatIndexRoute: typeof FormatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/format/': {
      id: '/format/'
      path: '/format'
      fullPath: '/format'
      preLoaderRoute: typeof FormatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/': {
      id: '/author/'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$blogId': {
      id: '/blogs/$blogId'
      path: '/blogs/$blogId'
      fullPath: '/blogs/$blogId'
      preLoaderRoute: typeof BlogsBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/import': {
      id: '/author/import'
      path: '/author/import'
      fullPath: '/author/import'
      preLoaderRoute: typeof AuthorImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/user-settings/': {
      id: '/dashboard/user-settings/'
      path: '/user-settings'
      fullPath: '/dashboard/user-settings'
      preLoaderRoute: typeof DashboardUserSettingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/learning/': {
      id: '/dashboard/learning/'
      path: '/learning'
      fullPath: '/dashboard/learning'
      preLoaderRoute: typeof DashboardLearningIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/essentials/': {
      id: '/dashboard/essentials/'
      path: '/essentials'
      fullPath: '/dashboard/essentials'
      preLoaderRoute: typeof DashboardEssentialsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/chat/': {
      id: '/dashboard/chat/'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/calculators/': {
      id: '/dashboard/calculators/'
      path: '/calculators'
      fullPath: '/dashboard/calculators'
      preLoaderRoute: typeof DashboardCalculatorsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/_layout/': {
      id: '/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardLayoutIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/calculators/saving-goals-calculator': {
      id: '/dashboard/calculators/saving-goals-calculator'
      path: '/calculators/saving-goals-calculator'
      fullPath: '/dashboard/calculators/saving-goals-calculator'
      preLoaderRoute: typeof DashboardCalculatorsSavingGoalsCalculatorRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/calculators/retirement-calculator': {
      id: '/dashboard/calculators/retirement-calculator'
      path: '/calculators/retirement-calculator'
      fullPath: '/dashboard/calculators/retirement-calculator'
      preLoaderRoute: typeof DashboardCalculatorsRetirementCalculatorRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/calculators/mortgage-calculator': {
      id: '/dashboard/calculators/mortgage-calculator'
      path: '/calculators/mortgage-calculator'
      fullPath: '/dashboard/calculators/mortgage-calculator'
      preLoaderRoute: typeof DashboardCalculatorsMortgageCalculatorRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/calculators/investment-calculator': {
      id: '/dashboard/calculators/investment-calculator'
      path: '/calculators/investment-calculator'
      fullPath: '/dashboard/calculators/investment-calculator'
      preLoaderRoute: typeof DashboardCalculatorsInvestmentCalculatorRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/calculators/compound-calculator': {
      id: '/dashboard/calculators/compound-calculator'
      path: '/calculators/compound-calculator'
      fullPath: '/dashboard/calculators/compound-calculator'
      preLoaderRoute: typeof DashboardCalculatorsCompoundCalculatorRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/calculators/auto-loan-calculator': {
      id: '/dashboard/calculators/auto-loan-calculator'
      path: '/calculators/auto-loan-calculator'
      fullPath: '/dashboard/calculators/auto-loan-calculator'
      preLoaderRoute: typeof DashboardCalculatorsAutoLoanCalculatorRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/learning/$courseId/': {
      id: '/dashboard/learning/$courseId/'
      path: '/learning/$courseId'
      fullPath: '/dashboard/learning/$courseId'
      preLoaderRoute: typeof DashboardLearningCourseIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/essentials/$courseId/': {
      id: '/dashboard/essentials/$courseId/'
      path: '/essentials/$courseId'
      fullPath: '/dashboard/essentials/$courseId'
      preLoaderRoute: typeof DashboardEssentialsCourseIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/learning/$courseId/lesson/$lessonId': {
      id: '/dashboard/learning/$courseId/lesson/$lessonId'
      path: '/learning/$courseId/lesson/$lessonId'
      fullPath: '/dashboard/learning/$courseId/lesson/$lessonId'
      preLoaderRoute: typeof DashboardLearningCourseIdLessonLessonIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/essentials/$courseId/lesson/$lessonId': {
      id: '/dashboard/essentials/$courseId/lesson/$lessonId'
      path: '/essentials/$courseId/lesson/$lessonId'
      fullPath: '/dashboard/essentials/$courseId/lesson/$lessonId'
      preLoaderRoute: typeof DashboardEssentialsCourseIdLessonLessonIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardCalculatorsAutoLoanCalculatorRoute: typeof DashboardCalculatorsAutoLoanCalculatorRoute
  DashboardCalculatorsCompoundCalculatorRoute: typeof DashboardCalculatorsCompoundCalculatorRoute
  DashboardCalculatorsInvestmentCalculatorRoute: typeof DashboardCalculatorsInvestmentCalculatorRoute
  DashboardCalculatorsMortgageCalculatorRoute: typeof DashboardCalculatorsMortgageCalculatorRoute
  DashboardCalculatorsRetirementCalculatorRoute: typeof DashboardCalculatorsRetirementCalculatorRoute
  DashboardCalculatorsSavingGoalsCalculatorRoute: typeof DashboardCalculatorsSavingGoalsCalculatorRoute
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
  DashboardCalculatorsIndexRoute: typeof DashboardCalculatorsIndexRoute
  DashboardChatIndexRoute: typeof DashboardChatIndexRoute
  DashboardEssentialsIndexRoute: typeof DashboardEssentialsIndexRoute
  DashboardLearningIndexRoute: typeof DashboardLearningIndexRoute
  DashboardUserSettingsIndexRoute: typeof DashboardUserSettingsIndexRoute
  DashboardEssentialsCourseIdIndexRoute: typeof DashboardEssentialsCourseIdIndexRoute
  DashboardLearningCourseIdIndexRoute: typeof DashboardLearningCourseIdIndexRoute
  DashboardEssentialsCourseIdLessonLessonIdRoute: typeof DashboardEssentialsCourseIdLessonLessonIdRoute
  DashboardLearningCourseIdLessonLessonIdRoute: typeof DashboardLearningCourseIdLessonLessonIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCalculatorsAutoLoanCalculatorRoute:
    DashboardCalculatorsAutoLoanCalculatorRoute,
  DashboardCalculatorsCompoundCalculatorRoute:
    DashboardCalculatorsCompoundCalculatorRoute,
  DashboardCalculatorsInvestmentCalculatorRoute:
    DashboardCalculatorsInvestmentCalculatorRoute,
  DashboardCalculatorsMortgageCalculatorRoute:
    DashboardCalculatorsMortgageCalculatorRoute,
  DashboardCalculatorsRetirementCalculatorRoute:
    DashboardCalculatorsRetirementCalculatorRoute,
  DashboardCalculatorsSavingGoalsCalculatorRoute:
    DashboardCalculatorsSavingGoalsCalculatorRoute,
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
  DashboardCalculatorsIndexRoute: DashboardCalculatorsIndexRoute,
  DashboardChatIndexRoute: DashboardChatIndexRoute,
  DashboardEssentialsIndexRoute: DashboardEssentialsIndexRoute,
  DashboardLearningIndexRoute: DashboardLearningIndexRoute,
  DashboardUserSettingsIndexRoute: DashboardUserSettingsIndexRoute,
  DashboardEssentialsCourseIdIndexRoute: DashboardEssentialsCourseIdIndexRoute,
  DashboardLearningCourseIdIndexRoute: DashboardLearningCourseIdIndexRoute,
  DashboardEssentialsCourseIdLessonLessonIdRoute:
    DashboardEssentialsCourseIdLessonLessonIdRoute,
  DashboardLearningCourseIdLessonLessonIdRoute:
    DashboardLearningCourseIdLessonLessonIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface RegisterRouteRouteChildren {
  RegisterIndexRoute: typeof RegisterIndexRoute
}

const RegisterRouteRouteChildren: RegisterRouteRouteChildren = {
  RegisterIndexRoute: RegisterIndexRoute,
}

const RegisterRouteRouteWithChildren = RegisterRouteRoute._addFileChildren(
  RegisterRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  RegisterRouteRoute: RegisterRouteRouteWithChildren,
  CookiePolicyRoute: CookiePolicyRoute,
  IntroRoute: IntroRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  AuthorImportRoute: AuthorImportRoute,
  BlogsBlogIdRoute: BlogsBlogIdRoute,
  AuthorIndexRoute: AuthorIndexRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  FormatIndexRoute: FormatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
