/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as UserSettingsRouteRouteImport } from './routes/user-settings/route'
import { Route as RegisterRouteRouteImport } from './routes/register/route'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserSettingsIndexRouteImport } from './routes/user-settings/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LearningIndexRouteImport } from './routes/learning/index'
import { Route as FormatIndexRouteImport } from './routes/format/index'
import { Route as CalculatorsIndexRouteImport } from './routes/calculators/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as AuthorIndexRouteImport } from './routes/author/index'
import { Route as CalculatorsSavingGoalsCalculatorRouteImport } from './routes/calculators/saving-goals-calculator'
import { Route as CalculatorsRetirementCalculatorRouteImport } from './routes/calculators/retirement-calculator'
import { Route as CalculatorsMortgageCalculatorRouteImport } from './routes/calculators/mortgage-calculator'
import { Route as CalculatorsInvestmentCalculatorRouteImport } from './routes/calculators/investment-calculator'
import { Route as CalculatorsCompoundCalculatorRouteImport } from './routes/calculators/compound-calculator'
import { Route as CalculatorsAutoLoanCalculatorRouteImport } from './routes/calculators/auto-loan-calculator'
import { Route as BlogsBlogIdRouteImport } from './routes/blogs/$blogId'
import { Route as AuthorImportRouteImport } from './routes/author/import'
import { Route as LearningCourseIdIndexRouteImport } from './routes/learning/$courseId/index'
import { Route as AuthorCourseCourseIdRouteImport } from './routes/author/course/$courseId'
import { Route as LearningCourseIdLessonLessonIdRouteImport } from './routes/learning/$courseId/lesson/$lessonId'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSettingsRouteRoute = UserSettingsRouteRouteImport.update({
  id: '/user-settings',
  path: '/user-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRouteRoute = RegisterRouteRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSettingsIndexRoute = UserSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserSettingsRouteRoute,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRouteRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const LearningIndexRoute = LearningIndexRouteImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormatIndexRoute = FormatIndexRouteImport.update({
  id: '/format/',
  path: '/format/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsIndexRoute = CalculatorsIndexRouteImport.update({
  id: '/calculators/',
  path: '/calculators/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorIndexRoute = AuthorIndexRouteImport.update({
  id: '/author/',
  path: '/author/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsSavingGoalsCalculatorRoute =
  CalculatorsSavingGoalsCalculatorRouteImport.update({
    id: '/calculators/saving-goals-calculator',
    path: '/calculators/saving-goals-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculatorsRetirementCalculatorRoute =
  CalculatorsRetirementCalculatorRouteImport.update({
    id: '/calculators/retirement-calculator',
    path: '/calculators/retirement-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculatorsMortgageCalculatorRoute =
  CalculatorsMortgageCalculatorRouteImport.update({
    id: '/calculators/mortgage-calculator',
    path: '/calculators/mortgage-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculatorsInvestmentCalculatorRoute =
  CalculatorsInvestmentCalculatorRouteImport.update({
    id: '/calculators/investment-calculator',
    path: '/calculators/investment-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculatorsCompoundCalculatorRoute =
  CalculatorsCompoundCalculatorRouteImport.update({
    id: '/calculators/compound-calculator',
    path: '/calculators/compound-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculatorsAutoLoanCalculatorRoute =
  CalculatorsAutoLoanCalculatorRouteImport.update({
    id: '/calculators/auto-loan-calculator',
    path: '/calculators/auto-loan-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsBlogIdRoute = BlogsBlogIdRouteImport.update({
  id: '/blogs/$blogId',
  path: '/blogs/$blogId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorImportRoute = AuthorImportRouteImport.update({
  id: '/author/import',
  path: '/author/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningCourseIdIndexRoute = LearningCourseIdIndexRouteImport.update({
  id: '/learning/$courseId/',
  path: '/learning/$courseId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorCourseCourseIdRoute = AuthorCourseCourseIdRouteImport.update({
  id: '/author/course/$courseId',
  path: '/author/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningCourseIdLessonLessonIdRoute =
  LearningCourseIdLessonLessonIdRouteImport.update({
    id: '/learning/$courseId/lesson/$lessonId',
    path: '/learning/$courseId/lesson/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/register': typeof RegisterRouteRouteWithChildren
  '/user-settings': typeof UserSettingsRouteRouteWithChildren
  '/chat': typeof ChatRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/intro': typeof IntroRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/author/import': typeof AuthorImportRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/calculators/auto-loan-calculator': typeof CalculatorsAutoLoanCalculatorRoute
  '/calculators/compound-calculator': typeof CalculatorsCompoundCalculatorRoute
  '/calculators/investment-calculator': typeof CalculatorsInvestmentCalculatorRoute
  '/calculators/mortgage-calculator': typeof CalculatorsMortgageCalculatorRoute
  '/calculators/retirement-calculator': typeof CalculatorsRetirementCalculatorRoute
  '/calculators/saving-goals-calculator': typeof CalculatorsSavingGoalsCalculatorRoute
  '/author': typeof AuthorIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/calculators': typeof CalculatorsIndexRoute
  '/format': typeof FormatIndexRoute
  '/learning': typeof LearningIndexRoute
  '/login/': typeof LoginIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/user-settings/': typeof UserSettingsIndexRoute
  '/author/course/$courseId': typeof AuthorCourseCourseIdRoute
  '/learning/$courseId': typeof LearningCourseIdIndexRoute
  '/learning/$courseId/lesson/$lessonId': typeof LearningCourseIdLessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/intro': typeof IntroRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/author/import': typeof AuthorImportRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/calculators/auto-loan-calculator': typeof CalculatorsAutoLoanCalculatorRoute
  '/calculators/compound-calculator': typeof CalculatorsCompoundCalculatorRoute
  '/calculators/investment-calculator': typeof CalculatorsInvestmentCalculatorRoute
  '/calculators/mortgage-calculator': typeof CalculatorsMortgageCalculatorRoute
  '/calculators/retirement-calculator': typeof CalculatorsRetirementCalculatorRoute
  '/calculators/saving-goals-calculator': typeof CalculatorsSavingGoalsCalculatorRoute
  '/author': typeof AuthorIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/calculators': typeof CalculatorsIndexRoute
  '/format': typeof FormatIndexRoute
  '/learning': typeof LearningIndexRoute
  '/login': typeof LoginIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/register': typeof RegisterIndexRoute
  '/user-settings': typeof UserSettingsIndexRoute
  '/author/course/$courseId': typeof AuthorCourseCourseIdRoute
  '/learning/$courseId': typeof LearningCourseIdIndexRoute
  '/learning/$courseId/lesson/$lessonId': typeof LearningCourseIdLessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/register': typeof RegisterRouteRouteWithChildren
  '/user-settings': typeof UserSettingsRouteRouteWithChildren
  '/chat': typeof ChatRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/intro': typeof IntroRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/author/import': typeof AuthorImportRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/calculators/auto-loan-calculator': typeof CalculatorsAutoLoanCalculatorRoute
  '/calculators/compound-calculator': typeof CalculatorsCompoundCalculatorRoute
  '/calculators/investment-calculator': typeof CalculatorsInvestmentCalculatorRoute
  '/calculators/mortgage-calculator': typeof CalculatorsMortgageCalculatorRoute
  '/calculators/retirement-calculator': typeof CalculatorsRetirementCalculatorRoute
  '/calculators/saving-goals-calculator': typeof CalculatorsSavingGoalsCalculatorRoute
  '/author/': typeof AuthorIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/calculators/': typeof CalculatorsIndexRoute
  '/format/': typeof FormatIndexRoute
  '/learning/': typeof LearningIndexRoute
  '/login/': typeof LoginIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/user-settings/': typeof UserSettingsIndexRoute
  '/author/course/$courseId': typeof AuthorCourseCourseIdRoute
  '/learning/$courseId/': typeof LearningCourseIdIndexRoute
  '/learning/$courseId/lesson/$lessonId': typeof LearningCourseIdLessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/user-settings'
    | '/chat'
    | '/cookie-policy'
    | '/intro'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/author/import'
    | '/blogs/$blogId'
    | '/calculators/auto-loan-calculator'
    | '/calculators/compound-calculator'
    | '/calculators/investment-calculator'
    | '/calculators/mortgage-calculator'
    | '/calculators/retirement-calculator'
    | '/calculators/saving-goals-calculator'
    | '/author'
    | '/blogs'
    | '/calculators'
    | '/format'
    | '/learning'
    | '/login/'
    | '/onboarding/'
    | '/profile/'
    | '/register/'
    | '/user-settings/'
    | '/author/course/$courseId'
    | '/learning/$courseId'
    | '/learning/$courseId/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/cookie-policy'
    | '/intro'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/author/import'
    | '/blogs/$blogId'
    | '/calculators/auto-loan-calculator'
    | '/calculators/compound-calculator'
    | '/calculators/investment-calculator'
    | '/calculators/mortgage-calculator'
    | '/calculators/retirement-calculator'
    | '/calculators/saving-goals-calculator'
    | '/author'
    | '/blogs'
    | '/calculators'
    | '/format'
    | '/learning'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/user-settings'
    | '/author/course/$courseId'
    | '/learning/$courseId'
    | '/learning/$courseId/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/user-settings'
    | '/chat'
    | '/cookie-policy'
    | '/intro'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/author/import'
    | '/blogs/$blogId'
    | '/calculators/auto-loan-calculator'
    | '/calculators/compound-calculator'
    | '/calculators/investment-calculator'
    | '/calculators/mortgage-calculator'
    | '/calculators/retirement-calculator'
    | '/calculators/saving-goals-calculator'
    | '/author/'
    | '/blogs/'
    | '/calculators/'
    | '/format/'
    | '/learning/'
    | '/login/'
    | '/onboarding/'
    | '/profile/'
    | '/register/'
    | '/user-settings/'
    | '/author/course/$courseId'
    | '/learning/$courseId/'
    | '/learning/$courseId/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  RegisterRouteRoute: typeof RegisterRouteRouteWithChildren
  UserSettingsRouteRoute: typeof UserSettingsRouteRouteWithChildren
  ChatRoute: typeof ChatRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  IntroRoute: typeof IntroRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  AuthorImportRoute: typeof AuthorImportRoute
  BlogsBlogIdRoute: typeof BlogsBlogIdRoute
  CalculatorsAutoLoanCalculatorRoute: typeof CalculatorsAutoLoanCalculatorRoute
  CalculatorsCompoundCalculatorRoute: typeof CalculatorsCompoundCalculatorRoute
  CalculatorsInvestmentCalculatorRoute: typeof CalculatorsInvestmentCalculatorRoute
  CalculatorsMortgageCalculatorRoute: typeof CalculatorsMortgageCalculatorRoute
  CalculatorsRetirementCalculatorRoute: typeof CalculatorsRetirementCalculatorRoute
  CalculatorsSavingGoalsCalculatorRoute: typeof CalculatorsSavingGoalsCalculatorRoute
  AuthorIndexRoute: typeof AuthorIndexRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  CalculatorsIndexRoute: typeof CalculatorsIndexRoute
  FormatIndexRoute: typeof FormatIndexRoute
  LearningIndexRoute: typeof LearningIndexRoute
  AuthorCourseCourseIdRoute: typeof AuthorCourseCourseIdRoute
  LearningCourseIdIndexRoute: typeof LearningCourseIdIndexRoute
  LearningCourseIdLessonLessonIdRoute: typeof LearningCourseIdLessonLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-settings': {
      id: '/user-settings'
      path: '/user-settings'
      fullPath: '/user-settings'
      preLoaderRoute: typeof UserSettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-settings/': {
      id: '/user-settings/'
      path: '/'
      fullPath: '/user-settings/'
      preLoaderRoute: typeof UserSettingsIndexRouteImport
      parentRoute: typeof UserSettingsRouteRoute
    }
    '/register/': {
      id: '/register/'
      path: '/'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/learning/': {
      id: '/learning/'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/format/': {
      id: '/format/'
      path: '/format'
      fullPath: '/format'
      preLoaderRoute: typeof FormatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/': {
      id: '/calculators/'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/': {
      id: '/author/'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/saving-goals-calculator': {
      id: '/calculators/saving-goals-calculator'
      path: '/calculators/saving-goals-calculator'
      fullPath: '/calculators/saving-goals-calculator'
      preLoaderRoute: typeof CalculatorsSavingGoalsCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/retirement-calculator': {
      id: '/calculators/retirement-calculator'
      path: '/calculators/retirement-calculator'
      fullPath: '/calculators/retirement-calculator'
      preLoaderRoute: typeof CalculatorsRetirementCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/mortgage-calculator': {
      id: '/calculators/mortgage-calculator'
      path: '/calculators/mortgage-calculator'
      fullPath: '/calculators/mortgage-calculator'
      preLoaderRoute: typeof CalculatorsMortgageCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/investment-calculator': {
      id: '/calculators/investment-calculator'
      path: '/calculators/investment-calculator'
      fullPath: '/calculators/investment-calculator'
      preLoaderRoute: typeof CalculatorsInvestmentCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/compound-calculator': {
      id: '/calculators/compound-calculator'
      path: '/calculators/compound-calculator'
      fullPath: '/calculators/compound-calculator'
      preLoaderRoute: typeof CalculatorsCompoundCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/auto-loan-calculator': {
      id: '/calculators/auto-loan-calculator'
      path: '/calculators/auto-loan-calculator'
      fullPath: '/calculators/auto-loan-calculator'
      preLoaderRoute: typeof CalculatorsAutoLoanCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$blogId': {
      id: '/blogs/$blogId'
      path: '/blogs/$blogId'
      fullPath: '/blogs/$blogId'
      preLoaderRoute: typeof BlogsBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/import': {
      id: '/author/import'
      path: '/author/import'
      fullPath: '/author/import'
      preLoaderRoute: typeof AuthorImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/$courseId/': {
      id: '/learning/$courseId/'
      path: '/learning/$courseId'
      fullPath: '/learning/$courseId'
      preLoaderRoute: typeof LearningCourseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/course/$courseId': {
      id: '/author/course/$courseId'
      path: '/author/course/$courseId'
      fullPath: '/author/course/$courseId'
      preLoaderRoute: typeof AuthorCourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/$courseId/lesson/$lessonId': {
      id: '/learning/$courseId/lesson/$lessonId'
      path: '/learning/$courseId/lesson/$lessonId'
      fullPath: '/learning/$courseId/lesson/$lessonId'
      preLoaderRoute: typeof LearningCourseIdLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LoginRouteRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface ProfileRouteRouteChildren {
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

interface RegisterRouteRouteChildren {
  RegisterIndexRoute: typeof RegisterIndexRoute
}

const RegisterRouteRouteChildren: RegisterRouteRouteChildren = {
  RegisterIndexRoute: RegisterIndexRoute,
}

const RegisterRouteRouteWithChildren = RegisterRouteRoute._addFileChildren(
  RegisterRouteRouteChildren,
)

interface UserSettingsRouteRouteChildren {
  UserSettingsIndexRoute: typeof UserSettingsIndexRoute
}

const UserSettingsRouteRouteChildren: UserSettingsRouteRouteChildren = {
  UserSettingsIndexRoute: UserSettingsIndexRoute,
}

const UserSettingsRouteRouteWithChildren =
  UserSettingsRouteRoute._addFileChildren(UserSettingsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRouteRoute: LoginRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  RegisterRouteRoute: RegisterRouteRouteWithChildren,
  UserSettingsRouteRoute: UserSettingsRouteRouteWithChildren,
  ChatRoute: ChatRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  IntroRoute: IntroRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  AuthorImportRoute: AuthorImportRoute,
  BlogsBlogIdRoute: BlogsBlogIdRoute,
  CalculatorsAutoLoanCalculatorRoute: CalculatorsAutoLoanCalculatorRoute,
  CalculatorsCompoundCalculatorRoute: CalculatorsCompoundCalculatorRoute,
  CalculatorsInvestmentCalculatorRoute: CalculatorsInvestmentCalculatorRoute,
  CalculatorsMortgageCalculatorRoute: CalculatorsMortgageCalculatorRoute,
  CalculatorsRetirementCalculatorRoute: CalculatorsRetirementCalculatorRoute,
  CalculatorsSavingGoalsCalculatorRoute: CalculatorsSavingGoalsCalculatorRoute,
  AuthorIndexRoute: AuthorIndexRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  CalculatorsIndexRoute: CalculatorsIndexRoute,
  FormatIndexRoute: FormatIndexRoute,
  LearningIndexRoute: LearningIndexRoute,
  AuthorCourseCourseIdRoute: AuthorCourseCourseIdRoute,
  LearningCourseIdIndexRoute: LearningCourseIdIndexRoute,
  LearningCourseIdLessonLessonIdRoute: LearningCourseIdLessonLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
