create table if not exists public.notification_capture_classifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  event_key text not null,
  source_package text not null,
  source_app_label text,
  status text not null check (status in ('processing', 'ignored', 'saved', 'failed')),
  decision text,
  reason_code text,
  subtype text,
  confidence numeric,
  model text,
  result jsonb,
  expense_id uuid references public.expenses(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, event_key)
);

create index if not exists idx_notification_capture_classifications_user_created
  on public.notification_capture_classifications(user_id, created_at desc);

create table if not exists public.notification_capture_ai_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_id uuid not null references public.notification_capture_classifications(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists idx_notification_capture_ai_attempts_user_created
  on public.notification_capture_ai_attempts(user_id, created_at desc);

alter table public.notification_capture_classifications enable row level security;
revoke all on table public.notification_capture_classifications from public, anon, authenticated;
grant all on table public.notification_capture_classifications to service_role;
alter table public.notification_capture_ai_attempts enable row level security;
revoke all on table public.notification_capture_ai_attempts from public, anon, authenticated;
grant all on table public.notification_capture_ai_attempts to service_role;

create or replace function public.claim_notification_capture_classification(
  p_user_id uuid,
  p_event_key text,
  p_source_package text,
  p_source_app_label text,
  p_hourly_limit integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
  v_existing public.notification_capture_classifications%rowtype;
  v_event_id uuid;
  v_recent_count integer;
  v_has_existing boolean := false;
begin
  if p_user_id is null
    or nullif(trim(coalesce(p_event_key, '')), '') is null
    or nullif(trim(coalesce(p_source_package, '')), '') is null
  then
    raise exception 'Invalid notification classification claim';
  end if;

  perform pg_advisory_xact_lock(
    hashtext('notification-classification|' || p_user_id::text)::bigint
  );

  select *
  into v_existing
  from public.notification_capture_classifications
  where user_id = p_user_id
    and event_key = p_event_key
  limit 1;

  v_has_existing := found;
  if v_has_existing then
    if v_existing.status in ('ignored', 'saved') and v_existing.result is not null then
      return jsonb_build_object(
        'status', 'cached',
        'result', v_existing.result
      );
    end if;

    if v_existing.status = 'processing'
      and v_existing.updated_at >= v_now - interval '10 minutes'
    then
      return jsonb_build_object('status', 'processing');
    end if;
  end if;

  select count(*)::integer
  into v_recent_count
  from public.notification_capture_ai_attempts
  where user_id = p_user_id
    and created_at >= v_now - interval '1 hour';

  if v_recent_count >= greatest(1, p_hourly_limit) then
    return jsonb_build_object('status', 'rate_limited');
  end if;

  if v_has_existing then
    update public.notification_capture_classifications
    set status = 'processing',
        result = null,
        updated_at = v_now
    where id = v_existing.id
    returning id into v_event_id;
  else
    insert into public.notification_capture_classifications (
      user_id,
      event_key,
      source_package,
      source_app_label,
      status,
      created_at,
      updated_at
    ) values (
      p_user_id,
      p_event_key,
      p_source_package,
      nullif(trim(coalesce(p_source_app_label, '')), ''),
      'processing',
      v_now,
      v_now
    )
    returning id into v_event_id;
  end if;

  insert into public.notification_capture_ai_attempts (
    user_id,
    event_id,
    created_at
  ) values (
    p_user_id,
    v_event_id,
    v_now
  );

  return jsonb_build_object('status', 'claimed', 'eventId', v_event_id);
end;
$$;

revoke all on function public.claim_notification_capture_classification(uuid, text, text, text, integer) from public, anon, authenticated;
grant execute on function public.claim_notification_capture_classification(uuid, text, text, text, integer) to service_role;

create or replace function public.cleanup_notification_capture_classifications()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deleted integer;
begin
  delete from public.notification_capture_ai_attempts
  where created_at < now() - interval '1 day';

  delete from public.notification_capture_classifications
  where (
      status = 'processing'
      and updated_at < now() - interval '1 day'
    )
    or (
      status <> 'processing'
      and updated_at < now() - interval '7 days'
    );
  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$$;

revoke all on function public.cleanup_notification_capture_classifications() from public, anon, authenticated;
grant execute on function public.cleanup_notification_capture_classifications() to service_role;

create extension if not exists pg_cron;

do $$
begin
  if exists (
    select 1 from cron.job
    where jobname = 'notification-capture-classification-cleanup'
  ) then
    perform cron.unschedule('notification-capture-classification-cleanup');
  end if;

  perform cron.schedule(
    'notification-capture-classification-cleanup',
    '17 3 * * *',
    $job$select public.cleanup_notification_capture_classifications();$job$
  );
end;
$$;

create or replace function public.android_wallet_capture_source_class(
  p_package text,
  p_app_label text default null
)
returns text
language sql
immutable
as $$
  select case
    when public.is_android_wallet_source(p_package, p_app_label) then 'wallet'
    when lower(coalesce(p_package, '')) in (
      'com.google.android.gm',
      'com.microsoft.office.outlook',
      'com.samsung.android.email.provider',
      'com.yahoo.mobile.client.android.mail',
      'com.fsck.k9'
    )
      or lower(coalesce(p_app_label, '')) ~ '\m(?:gmail|outlook|email|mail)\M'
      then 'email'
    when lower(coalesce(p_package, '')) in (
      'com.google.android.apps.messaging',
      'com.samsung.android.messaging',
      'com.android.mms',
      'com.android.messaging'
    )
      or lower(coalesce(p_app_label, '')) ~ '\m(?:messages|messaging|sms|text messages)\M'
      then 'sms'
    when nullif(trim(coalesce(p_package, '')), '') is not null then 'bank'
    else 'unknown'
  end;
$$;

update public.wallet_capture_events
set source_class = public.android_wallet_capture_source_class(source_package, source_app_label)
where source_class is distinct from public.android_wallet_capture_source_class(source_package, source_app_label);

revoke all on function public.android_wallet_capture_source_class(text, text) from public, anon, authenticated;
grant execute on function public.android_wallet_capture_source_class(text, text) to service_role;
