create table if not exists public.pdf_analysis_cache (
  hash text primary key,
  result jsonb not null,
  created_at timestamptz not null default timezone('utc', now()),
  expires_at timestamptz not null
);

create index if not exists pdf_analysis_cache_expires_at_idx
  on public.pdf_analysis_cache (expires_at);

create table if not exists public.pdf_analysis_logs (
  id bigint generated by default as identity primary key,
  request_id uuid not null,
  hash text not null,
  document_type text not null,
  page_count integer not null default 0,
  extraction_strategy text not null,
  ai_provider text,
  input_tokens integer,
  output_tokens integer,
  latency_ms integer,
  cache_hit boolean not null default false,
  anomaly jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists pdf_analysis_logs_request_id_idx
  on public.pdf_analysis_logs (request_id);

create index if not exists pdf_analysis_logs_created_at_idx
  on public.pdf_analysis_logs (created_at desc);

create index if not exists pdf_analysis_logs_hash_idx
  on public.pdf_analysis_logs (hash);

alter table public.pdf_analysis_cache enable row level security;
alter table public.pdf_analysis_logs enable row level security;
