import { serve } from "https://deno.land/std@0.177.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.7.1";
import { corsHeaders } from "../shared/cors.ts";
import { logUserActivity, type ActivityData } from "../shared/activity-logger.ts";
import { actions } from "../shared/update-reward-actions/reward-actions.ts";

// Initialize Supabase client
const supabaseClient = createClient(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
);

interface TimelineManagerRequest {
  action: 'update_timeline' | 'extend_timeline' | 'adjust_target';
  goalId: string;
  userId: string;
  payload: {
    target_date?: string;
    original_target_date?: string;
    reason?: string;
    auto_generated?: boolean;
    metadata?: {
      [key: string]: any;
    };
  };
}

interface GoalUpdateData {
  target_date?: string;
  updated_at?: string;
  [key: string]: any;
}

serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const { action, goalId, userId, payload }: TimelineManagerRequest = await req.json();

    console.log(`[goal-timeline-manager] Processing ${action} for goal ${goalId}`);

    if (!userId) {
      return new Response(JSON.stringify({ error: 'User ID is required' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    if (!goalId) {
      return new Response(JSON.stringify({ error: 'Goal ID is required' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // First, fetch the current goal to get existing data and calculate changes
    const { data: currentGoal, error: fetchError } = await supabaseClient
      .from('financial_goals')
      .select('*')
      .eq('id', goalId)
      .eq('user_id', userId)
      .single();

    if (fetchError) {
      console.error('Error fetching goal:', fetchError);
      return new Response(JSON.stringify({ error: 'Goal not found' }), {
        status: 404,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    let updateData: GoalUpdateData = {
      updated_at: new Date().toISOString(),
    };
    let activityAction: string = '';
    let activityMetadata: any = {
      goalId,
      goalTitle: currentGoal.title,
    };

    switch (action) {
      case 'update_timeline':
        if (!payload.target_date) {
          return new Response(JSON.stringify({ error: 'Target date is required for timeline update' }), {
            status: 400,
            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          });
        }

        updateData.target_date = payload.target_date;
        activityAction = actions.GOAL_TIMELINE_UPDATED;
        
        const originalDate = new Date(currentGoal.target_date);
        const newDate = new Date(payload.target_date);
        const daysDifference = Math.ceil((newDate.getTime() - originalDate.getTime()) / (1000 * 60 * 60 * 24));
        
        activityMetadata = {
          ...activityMetadata,
          originalTargetDate: currentGoal.target_date,
          newTargetDate: payload.target_date,
          daysDifference,
          isExtension: daysDifference > 0,
          reason: payload.reason,
          autoGenerated: payload.auto_generated || false,
        };
        break;

      case 'extend_timeline':
        if (!payload.target_date) {
          return new Response(JSON.stringify({ error: 'New target date is required for timeline extension' }), {
            status: 400,
            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          });
        }

        updateData.target_date = payload.target_date;
        activityAction = actions.GOAL_TIMELINE_EXTENDED;
        
        const extensionDays = Math.ceil((new Date(payload.target_date).getTime() - new Date(currentGoal.target_date).getTime()) / (1000 * 60 * 60 * 24));
        
        activityMetadata = {
          ...activityMetadata,
          originalTargetDate: currentGoal.target_date,
          newTargetDate: payload.target_date,
          extensionDays,
          reason: payload.reason,
          autoGenerated: payload.auto_generated || false,
        };
        break;

      case 'adjust_target':
        // This could handle more complex adjustments including target amount changes
        if (payload.target_date) {
          updateData.target_date = payload.target_date;
        }
        
        // Include any additional metadata from payload
        if (payload.metadata) {
          Object.assign(updateData, payload.metadata);
        }

        activityAction = actions.GOAL_TARGET_ADJUSTED;
        activityMetadata = {
          ...activityMetadata,
          originalTargetDate: currentGoal.target_date,
          newTargetDate: payload.target_date,
          adjustmentType: 'timeline',
          reason: payload.reason,
          autoGenerated: payload.auto_generated || false,
          ...payload.metadata,
        };
        break;

      default:
        return new Response(JSON.stringify({ error: 'Invalid action' }), {
          status: 400,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
    }

    // Update the goal in the database
    const { data, error } = await supabaseClient
      .from('financial_goals')
      .update(updateData)
      .eq('id', goalId)
      .eq('user_id', userId)
      .select()
      .single();

    if (error) {
      console.error('Supabase update error:', error);
      return new Response(JSON.stringify({ error: error.message }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Log the activity
    const activityData: ActivityData = {
      type: 'goal_management',
      action: activityAction,
      source: 'goal-timeline-manager',
      metadata: activityMetadata,
      timestamp: new Date().toISOString(),
    };
    
    const activityResult = await logUserActivity(supabaseClient, userId, activityData);

    if (!activityResult.success) {
      console.error('Failed to log activity:', activityResult.error);
      // Don't fail the request, just log the error
    }

    console.log(`[goal-timeline-manager] Successfully processed ${action} for goal ${goalId}`);

    return new Response(JSON.stringify({
      success: true,
      goal: data,
      activity_logged: activityResult.success,
      activity_id: activityResult.activity_id,
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (e) {
    console.error('Function error:', e);
    return new Response(JSON.stringify({ error: e.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});